### PR TITLE
Trying out pull requests

### PR DESCRIPTION
**Pull request by keyabarve**
Learning about pull requests with @luizirber 

## Checklist

- [ ] Is it mergeable?
- [ ] `make test` Did it pass the tests?
- [ ] `make coverage` Is the new code covered?
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
hi @keyabarve can this be closed?

**Comment by ctb** [comment]
bump.

**Comment by keyabarve** [comment]
@ctb Yes, I think we can close it.

**Comment by ctb** [comment]
please go ahead, then - you should be able to close it.

**Pull request closed without merging**
