### PR TITLE
[MRG] fix bug where `sourmash sketch ... --singleton -o output.sig` drops signatures

### LINKED ISSUE #1809: bug - when multiple input files are used with `sourmash sketch ... --singleton -o filename`, all but last are dropped
When using `sourmash sketch ... -o <filename> --singleton`, only the signatures from the last file are actually saved.

This occurs because `siglist` is reset in the `--singleton` if branch.

It looks like this bug was introduced in https://github.com/sourmash-bio/sourmash/pull/734.

### PR DESCRIPTION
**Pull request by ctb**
In https://github.com/sourmash-bio/sourmash/pull/734, we (I...) introduced a bug where the if branch for `--singleton` resets the list of signatures improperly, without saving them. This loses information and is Bad.

This PR adds a test for this and fixes the `_compute_individual` method in `command_compute.py` to properly save all the signatures. It also tries to clean up the code a bit. 

Fixes #1809.

NOTE: this bug has been present since sourmash v2.2.0. 🤯

### CODE REVIEW

**Comment by ctb** [comment]
This is ready for review @sourmash-bio/devs.

The code coverage % drop is because code was removed; all the code is covered as it was before.

**Comment by ctb** [comment]
ARGH and the python3.8 tests are failing because fix_lint is failing because darker has a bug in it:

```
   Traceback (most recent call last):
    File "/home/runner/.cache/pre-commit/repoz2blxa1f/py_env-python3/bin/darker", line 8, in <module>
      sys.exit(main())
    File "/home/runner/.cache/pre-commit/repoz2blxa1f/py_env-python3/lib/python3.8/site-packages/darker/__main__.py", line 196, in main
      args, config, config_nondefault = parse_command_line(argv)
    File "/home/runner/.cache/pre-commit/repoz2blxa1f/py_env-python3/lib/python3.8/site-packages/darker/command_line.py", line 163, in parse_command_line
      config = load_config(args.src)
    File "/home/runner/.cache/pre-commit/repoz2blxa1f/py_env-python3/lib/python3.8/site-packages/darker/config.py", line 37, in load_config
      path = find_project_root(tuple(srcs or ["."])) / "pyproject.toml"
  TypeError: unsupported operand type(s) for /: 'tuple' and 'str'
  
  Error: ERROR: InvocationError for command /home/runner/work/sourmash/sourmash/.tox/fix_lint/bin/pre-commit run --all-files --show-diff-on-failure (exited with code 1)
```

**Comment by taylorreiter** [comment]
soo wait to review?

**Comment by ctb** [comment]
no, I think it's fine to review, sorry :)

**Comment by ctb** [comment]
@sourmash-bio/devs ready for review.  I'll verify that the tests are only breaking because of non-PR related stuff before merging.

**Review by bluegenes — APPROVED** [review]
lgtm

**Pull request merged**
