### PR TITLE
MRG: make `sourmash plot` labels/indices arguments make sense

### LINKED ISSUE #2667: Differing dendrogram outputs from plot - `--labeltext` is honored differently by dendrogram and matrix outputs
Hello,

I'm currently having an issue where `sourmash plot` is outputting two different dendrograms. I've attached an example and the code I used below. I get the same issue with version 4.0.0.(using for some old work) and the latest version.  

```
sourmash compare -k=21 --output k21_all_compare --csv k21_all_compare.csv /home/b56j439/sourmash/all/sigs/*sig

sourmash plot k21_all_compare --labeltext new_labels.txt --csv k21_all_plot.csv
```

I've confirmed the `new_labels.txt ` contains the same labels in the same order as the original label file, I just wanted to remove the directory structure from the labels. 

k21_all_compare matrix
k21_all_compare dendro

### PR DESCRIPTION
**Pull request by ctb**
This PR rationalizes `sig plot` arguments for `--labels` (show names) and `--indices` (show numbers), and adds `--no-labels` and `--no-indices`, as follows. See https://github.com/sourmash-bio/sourmash/issues/2667 for motivating bug.

1. `sourmash plot compare-demo` - labels on dendrogram, labels on matrix ✅  (FIXED)

2. `sourmash plot compare-demo --labels` - labels on both dendrogram and matrix ✅ 

3. `sourmash plot compare-demo --indices` - indices on both dendrogram and matrix ✅ 

4. `sourmash plot compare-demo --labels --indices` - labels on both ✅ (FIXED - labels override indices)

New arguments from this PR:

5. `sourmash plot compare-demo --no-labels` - indices on both ✅ 

6. `sourmash plot compare-demo --no-labels --no-indices` - no labels/indices on either ✅ 

7. `sourmash plot compare-demo --no-indices` - labels on both ✅ 

The PR also simplifies some of the `plot` command code as well as code in `fig.py`.

TODO:
- [x] write some tests for new args
- [x] update documentation
- [x] check to see if notebook code should be updated

Fixes https://github.com/sourmash-bio/sourmash/issues/2667
Closes https://github.com/sourmash-bio/sourmash/pull/2672

### CODE REVIEW

**Comment by ctb** [comment]
Ready for review @sourmash-bio/devs !

Note that the code coverage annotations in the diff are not correct. Not sure what's going on there - I'm going to try rerunning the tests.

**Comment by ctb** [comment]
well, the [code cov report](https://app.codecov.io/gh/sourmash-bio/sourmash/pull/2790?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=checks&utm_campaign=pr+comments&utm_term=sourmash-bio) is correct, even if the github diff display is not. 🤷

**Comment by AnneliektH** [comment]
Arguments all work correctly for my data:
- --no-indices shows no indices, but shows labels
- --no-labels gives no labels, but shows indices
- --no-labels --no-indices gives neither
- --labels --indices chooses labels over indices.
- 
The way indices work make sense, but got me confused for a second, as it starts with 0, and i worked with a dataset named Sample_1 - Sample_10. Sample_1 is 0 in the indices, Sample_10 is 1 in the indices. Which makes sense from a computer perspective, but maybe less from a human perspective.

**Comment by ctb** [comment]
thanks @AnneliektH ! b90f7616 changes the indices to be 1-based. I'll merge when tests pass here!

**Pull request merged**
