### PR TITLE
[MRG] replace utils.TempDirectory with run tmp

### PR DESCRIPTION
**Pull request by hehouts**
Updated to `runtmp` in `test_cmd_signature.py`(1 test) and `test_index.py` (3  tests)

Chips away at #1386

### CODE REVIEW

**Comment by ctb** [comment]
your PR is looking good, @hehouts ! I think you're probably interested in `runtmp.last_result.status`, `.out`, and `.err`.

**Comment by ctb** [comment]
looking good!

**Comment by hehouts** [comment]
@ctb @bluegenes please review :)

The test print statements havent changed, so Im pretty sure theyre still working

**Review by bluegenes — APPROVED** [review]
looks great to me!

**Review by ctb — APPROVED** [review]
nice work!

**Comment by ctb** [comment]
@hehouts when it passes all the tests (I updated from latest again), please go ahead and merge ;)

**Pull request merged**
