### PR TITLE
[MRG] check to make sure that .zip files exist before trying to load from them.

### LINKED ISSUE #1774: bug in `sourmash.load_file_as_signatures(...)` when loading non-existent .zip file
This:
```
sourmash.load_file_as_signatures('foo87878.zip')
```
yields a confusing error about manifests, when `foo87878.zip` doesn't exist. I think it should instead say "this file doesn't exist" 😄

### PR DESCRIPTION
**Pull request by ctb**
This PR changes `ZipStorage.load(...)` to check to see if a zipfile exists before trying to open it. In turn, this means that an empty zipfile will no longer be _created_ by `ZipStorage` :)

Fixes https://github.com/sourmash-bio/sourmash/issues/1774

- [x] needs a new test for non-existent zip file!

### CODE REVIEW

**Comment by ctb** [comment]
Ready for review (and, assuming tests pass, merge :) -- @sourmash-bio/devs

**Review by mr-eyes — APPROVED** [review]
LGTM!

**Comment by mr-eyes** [comment]
I reran the Python tests.

**Comment by ctb** [comment]
k - looks like the tests are failing for legitimate reasons now :). so I gotta fix that.

**Pull request merged**
