### PR TITLE
[MRG] move variables inline in format strings

### PR DESCRIPTION
**Pull request by ctb**
Fixes issues noted by recent cargo lint.

Includes https://github.com/sourmash-bio/sourmash/pull/2416

### CODE REVIEW

**Comment by ctb** [comment]
@sourmash-bio/devs this is just lint fixing, so I'll merge this when the tests pass, unless someone stops me :)

**Comment by ctb** [comment]
It looks like this fails due to Rust minimum version, so we should not keep this up for merge. I'll close this for now and maybe @luizirber can rescue it if need be ;).

**Comment by luizirber** [comment]
yeah, this will only work on [1.58](https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html#captured-identifiers-in-format-strings)...

**Comment by ctb** [comment]
#2393 only updated to 1.56.1, not 1.58 😭

**Pull request closed without merging**
