### PR TITLE
[WIP] Updating `tests/test_sourmash.py::test_storage_convert` to use `runtmp` fixture instead of `utils.TempDirectory()`

### LINKED ISSUE #1734: update `tests/test_sourmash.py::test_storage_convert` to use `runtmp` fixture instead of `utils.TempDirectory()`
This is a continuation of  #1386.

Over in #1718, all of the tests were updated to use `runtmp` fixture instead of `utils.TempDirectory()`, except this one test, because IPFS needed to be installed to test this. 

In this issue, this test needs to be updated.

### PR DESCRIPTION
**Pull request by keyabarve**
Fixes #1734

### CODE REVIEW

**Comment by keyabarve** [comment]
@ctb I have updated the test and it passes now. Ready for review and merge!

**Comment by ctb** [comment]
please wait until the test passes via CI before asking for a merge :).

note that the test fails, and I think you still have some cleanup of the code to do.

**Comment by keyabarve** [comment]
@ctb The test is failing on Github with this error:
`Failed: DID NOT RAISE <class 'sourmash_tst_utils.SourmashCommandFailed'>`
but on my computer, it passes, and if I remove the `with pytest.raises(SourmashCommandFailed):` line, it fails.

**Comment by ctb** [comment]
> @ctb The test is failing on Github with this error:
> `Failed: DID NOT RAISE <class 'sourmash_tst_utils.SourmashCommandFailed'>`
> but on my computer, it passes, and if I remove the `with pytest.raises(SourmashCommandFailed):` line, it fails.

Yep. I think that implies that your IPFS configuration is still not working. That sourmash command should not fail if IPFS is running.

What confuses me is that the `if not status` line in the original code (`latest` branch) seems broken.  @luizirber am I reading this right, that the original test succeeded whether or not IPFS was working?

**Comment by ctb** [comment]
I think the correct code modification in the `latest` branch would be:
```
        if status:
            if "ipfs.exceptions.ConnectionError" in err:
                raise pytest.xfail('ipfs probably not running')
            if "No module named 'ipfshttpclient'" in err:
                raise pytest.xfail('ipfshttpclient module not installed')

```
maybe you could update the code in this PR to match (but using runtmp)?

**Comment by keyabarve** [comment]
> > @ctb The test is failing on Github with this error:
> > `Failed: DID NOT RAISE <class 'sourmash_tst_utils.SourmashCommandFailed'>`
> > but on my computer, it passes, and if I remove the `with pytest.raises(SourmashCommandFailed):` line, it fails.
> 
> Yep. I think that implies that your IPFS configuration is still not working. That sourmash command should not fail if IPFS is running.
> 
Right. What can II do to fix this?

**Comment by ctb** [comment]
> @ctb The test is failing on Github with this error:
> `Failed: DID NOT RAISE <class 'sourmash_tst_utils.SourmashCommandFailed'>`
> but on my computer, it passes, and if I remove the `with pytest.raises(SourmashCommandFailed):` line, it fails.

hi @keyabarve, ok, this is now the remaining line that seems to be causing problems.

## when ipfshttpclient is not installed

On my laptop, when I run:
```
py.test tests/test_sourmash.py::test_storage_convert -v
```
I get
```
>tests/test_sourmash.py::test_storage_convert XFAIL (ipfshttpclient module not installed)
```

which is correct - the sourmash command itself fails, but correctly catches that the import fails. 

## after installing ipfshttpclient

after
```
pip install ipfshttpclient
```
I get 
```
>tests/test_sourmash.py::test_storage_convert PASSED
```
which is incorrect - the sourmash command actually did fail, because I don't have IPFS running, but the string `ipfs.exceptions.ConnectionError` didn't get caught and raised as an xfail.

I don't have time to check this right now, but my prediction is that if I have IPFS running, the test will also fail, because runtmp.sourmash will succeed.

So you need to modify this command to work in all these situations - ipfshttpclient not installed, ipfshttpclient installed but IPFS not running, and ipfshttpclient installed and IPFS running.

So you can't use `runtmp.sourmash` because that requires that you know, in advance, if the command will succeed or fail.

Looking at the `RunnerContext` class in sourmash_tst_utils.py, I think you should switch to using `runtmp.run(...)` instead of `run_sourmash`, because that doesn't force this behavior.

You should also fix the name of the module - it's not `ipfs.exceptions` any more, it's `ipfshttpclient`.

**Comment by ctb** [comment]
So, to summarize - you'll need to test this in your dev environment for three different configurations, and make sure the test passes for all three configs:

1. ipfshttpclient Python module not installed
2. ipfshttpclient Python module installed but IPFS service not running
3. ipfshttpclient Python module installed and IPFS service running

For the purposes of making sure the test is actually testing stuff correctly, you should also verify that the test _fails_ in all three configs when 'sourmash storage convert' is broken.

**Comment by keyabarve** [comment]
> > @ctb The test is failing on Github with this error:
> > `Failed: DID NOT RAISE <class 'sourmash_tst_utils.SourmashCommandFailed'>`
> > but on my computer, it passes, and if I remove the `with pytest.raises(SourmashCommandFailed):` line, it fails.
> 
> hi @keyabarve, ok, this is now the remaining line that seems to be causing problems.
> 
> ## when ipfshttpclient is not installed
> On my laptop, when I run:
> 
> ```
> py.test tests/test_sourmash.py::test_storage_convert -v
> ```
> 
> I get
> 
> ```
> >tests/test_sourmash.py::test_storage_convert XFAIL (ipfshttpclient module not installed)
> ```
> 
> which is correct - the sourmash command itself fails, but correctly catches that the import fails.
> 
> ## after installing ipfshttpclient
> after
> 
> ```
> pip install ipfshttpclient
> ```
> 
> I get
> 
> ```
> >tests/test_sourmash.py::test_storage_convert PASSED
> ```
> 
> which is incorrect - the sourmash command actually did fail, because I don't have IPFS running, but the string `ipfs.exceptions.ConnectionError` didn't get caught and raised as an xfail.
> 
Right, I get the same thing too.

> I don't have time to check this right now, but my prediction is that if I have IPFS running, the test will also fail, because runtmp.sourmash will succeed.
> 
> So you need to modify this command to work in all these situations - ipfshttpclient not installed, ipfshttpclient installed but IPFS not running, and ipfshttpclient installed and IPFS running.
> 
> So you can't use `runtmp.sourmash` because that requires that you know, in advance, if the command will succeed or fail.
> 
> Looking at the `RunnerContext` class in sourmash_tst_utils.py, I think you should switch to using `runtmp.run(...)` instead of `run_sourmash`, because that doesn't force this behavior.
> 
Alright, I'll do that.

> You should also fix the name of the module - it's not `ipfs.exceptions` any more, it's `ipfshttpclient`.
>
Okay, thanks!

**Comment by keyabarve** [comment]
@ctb I made the changes you requested, but I was wondering what you meant by this: "You should also fix the name of the module - it's not ipfs.exceptions any more, it's ipfshttpclient." because I couldn't find any module with that name.

**Comment by ctb** [comment]
> @ctb I made the changes you requested, but I was wondering what you meant by this: "You should also fix the name of the module - it's not ipfs.exceptions any more, it's ipfshttpclient." because I couldn't find any module with that name.

it looks like you made the right change --

```
if "ipfshttpclient.ConnectionError" in runtmp.last_result.err:
```

-- what do you think that line is doing?

**Comment by ctb** [comment]
also, did you `pip install ipfshttpclient` and did it work? if so, what does "because I couldn't find any module with that name" mean - how did you look for it?

**Comment by keyabarve** [comment]
It's checking if the error raised by the command is the "ipfshttpclient.ConnectionError".

**Comment by keyabarve** [comment]
> also, did you `pip install ipfshttpclient` and did it work? if so, what does "because I couldn't find any module with that name" mean - how did you look for it?
>
I just looked for it in the codebase. I was looking for any place it has been imported/used within the code.

**Comment by keyabarve** [comment]
I already did `pip install ipfshttpclient` and this is what I get:
```
Requirement already satisfied: ipfshttpclient in /Users/keya/mambaforge/envs/sourmash_dev/lib/python3.9/site-packages (0.4.13.2)
Requirement already satisfied: six in /Users/keya/mambaforge/envs/sourmash_dev/lib/python3.9/site-packages (from ipfshttpclient) (1.15.0)
Requirement already satisfied: multiaddr>=0.0.7 in /Users/keya/mambaforge/envs/sourmash_dev/lib/python3.9/site-packages (from ipfshttpclient) (0.0.9)
Requirement already satisfied: requests>=2.11 in /Users/keya/mambaforge/envs/sourmash_dev/lib/python3.9/site-packages (from ipfshttpclient) (2.25.1)
Requirement already satisfied: varint in /Users/keya/mambaforge/envs/sourmash_dev/lib/python3.9/site-packages (from multiaddr>=0.0.7->ipfshttpclient) (1.0.2)
Requirement already satisfied: base58 in /Users/keya/mambaforge/envs/sourmash_dev/lib/python3.9/site-packages (from multiaddr>=0.0.7->ipfshttpclient) (2.1.0)
Requirement already satisfied: netaddr in /Users/keya/mambaforge/envs/sourmash_dev/lib/python3.9/site-packages (from multiaddr>=0.0.7->ipfshttpclient) (0.8.0)
Requirement already satisfied: chardet<5,>=3.0.2 in /Users/keya/mambaforge/envs/sourmash_dev/lib/python3.9/site-packages (from requests>=2.11->ipfshttpclient) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/keya/mambaforge/envs/sourmash_dev/lib/python3.9/site-packages (from requests>=2.11->ipfshttpclient) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/keya/mambaforge/envs/sourmash_dev/lib/python3.9/site-packages (from requests>=2.11->ipfshttpclient) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in /Users/keya/mambaforge/envs/sourmash_dev/lib/python3.9/site-packages (from requests>=2.11->ipfshttpclient) (2.10)
```

**Comment by ctb** [comment]
ok, so the module installed correctly in Python, which is good.

What does `git grep ipfshttpclient` give you? Do you see any place in the codebase where it's used?

**Comment by keyabarve** [comment]
I get this:
```
setup.cfg:    ipfshttpclient>=0.4.13
src/sourmash/sbt_storage.py:        import ipfshttpclient
src/sourmash/sbt_storage.py:        self.api = ipfshttpclient.connect(**self.ipfs_args)
tests/test_sbt.py:    ipfshttpclient = pytest.importorskip('ipfshttpclient')
tests/test_sbt.py:        except ipfshttpclient.exceptions.ConnectionError:
tests/test_sourmash.py:        if "ipfshttpclient.ConnectionError" in runtmp.last_result.err:
tests/test_sourmash.py:        if "No module named 'ipfshttpclient'" in runtmp.last_result.err:
tests/test_sourmash.py:            raise pytest.xfail('ipfshttpclient module not installed')
```
It's used in quite a few places in the codebase.

**Comment by keyabarve** [comment]
> @ctb I made the changes you requested, but I was wondering what you meant by this: "You should also fix the name of the module - it's not ipfs.exceptions any more, it's ipfshttpclient." because I couldn't find any module with that name.
>
Here, I meant I couldn't find the `ipfs.exceptions` module

**Comment by ctb** [comment]
On Thu, Sep 30, 2021 at 05:15:07PM -0700, Keya Barve wrote:
> > @ctb I made the changes you requested, but I was wondering what you meant by this: "You should also fix the name of the module - it's not ipfs.exceptions any more, it's ipfshttpclient." because I couldn't find any module with that name.
> >
> Here, I meant I couldn't find the `ipfs.exceptions` module

that's right, the module name has changed.

**Comment by keyabarve** [comment]
Alright!

**Comment by keyabarve** [comment]
@ctb @mr-eyes 
In this PR, I have 2 tests failing: 
1. `tests/test_sourmash.py:: test_do_compare_quiet` is failing on the PR, but not on my computer. Also, I'm not sure I understand what the error is and why it's failing.
2. `tests/test_sourmash.py:: test_storage_convert` is also failing. This is the error:
```
self.last_result = runscript(scriptname, args, **kwargs)
E       AssertionError: (-1, '', 'Traceback (most recent call last):\n  File "/Users/keya/sourmash/tests/sourmash_tst_utils.py", line 105, in runscript\n    status = _runscript(scriptname)\n  File "/Users/keya/sourmash/tests/sourmash_tst_utils.py", line 47, in _runscript\n    pkg_resources.load_entry_point("sourmash", \'console_scripts\', scriptname)()\n  File "/Users/keya/miniconda3/envs/sourmash_dev/lib/python3.10/site-packages/pkg_resources/__init__.py", line 479, in load_entry_point\n    return get_distribution(dist).load_entry_point(group, name)\n  File "/Users/keya/miniconda3/envs/sourmash_dev/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2850, in load_entry_point\n    raise ImportError("Entry point %r not found" % ((group, name),))\nImportError: Entry point (\'console_scripts\', \'storage\') not found\n')

tests/sourmash_tst_utils.py:205: AssertionError
```
I'm not sure how I can fix this error.

**Comment by ctb** [comment]
> @ctb @mr-eyes In this PR, I have 2 tests failing:
> 
>     1. `tests/test_sourmash.py:: test_do_compare_quiet` is failing on the PR, but not on my computer. Also, I'm not sure I understand what the error is and why it's failing.
> 
>     2. `tests/test_sourmash.py:: test_storage_convert` is also failing. This is the error:
> 
> 
> ```
> self.last_result = runscript(scriptname, args, **kwargs)
> E       AssertionError: (-1, '', 'Traceback (most recent call last):\n  File "/Users/keya/sourmash/tests/sourmash_tst_utils.py", line 105, in runscript\n    status = _runscript(scriptname)\n  File "/Users/keya/sourmash/tests/sourmash_tst_utils.py", line 47, in _runscript\n    pkg_resources.load_entry_point("sourmash", \'console_scripts\', scriptname)()\n  File "/Users/keya/miniconda3/envs/sourmash_dev/lib/python3.10/site-packages/pkg_resources/__init__.py", line 479, in load_entry_point\n    return get_distribution(dist).load_entry_point(group, name)\n  File "/Users/keya/miniconda3/envs/sourmash_dev/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2850, in load_entry_point\n    raise ImportError("Entry point %r not found" % ((group, name),))\nImportError: Entry point (\'console_scripts\', \'storage\') not found\n')
> 
> tests/sourmash_tst_utils.py:205: AssertionError
> ```
> 
> I'm not sure how I can fix this error.

fixed in https://github.com/sourmash-bio/sourmash/pull/1739/commits/d3b72d64c23e34e9cf05ce0ee1651a790990bb0c.

**Pull request merged**
