### PR TITLE
[MRG] add cibuildwheel to GitHub actions

### PR DESCRIPTION
**Pull request by ctb**
Since TravisCI is no longer working well for building wheels, let's give GitHub Actions a try!

- [ ] Is it mergeable?
- [ ] `make test` Did it pass the tests?
- [ ] `make coverage` Is the new code covered?
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by luizirber** [comment]
I'm taking over this PR and also bringing the remaining checks from Travis (no point in blocking PR merging because Travis is not running our builds)

**Comment by ctb** [comment]
oh thank god

**Comment by luizirber** [comment]
I disabled most tests from Travis, but didn't replace them yet with the GH actions version. I'll open a new PR for that, and leave this one only for fixing wheels

(travis tests are not being executed anyway, since we are over our quota =/)

**Comment by luizirber** [comment]
And codecov is failing because the Python tests are not being reported :grimacing: 

Ready for review and merge @ctb

**Comment by ctb** [comment]
I approve of it, but since I'm the original author I can't officially approve it for merge :). So... let's just merge when tests pass.

**Pull request merged**
