### PR TITLE
[MRG] update release instructions after v4.4.2

### PR DESCRIPTION
**Pull request by ctb**
This PR:
* adds `pip install build` in appropriate places
* improves instructions for steps that I repeatedly mess up
* adds a checklist for successful release checks
* adds draft release note categories / `git diff` instructions

ref https://github.com/sourmash-bio/sourmash/issues/2129

### CODE REVIEW

**Comment by ctb** [comment]
Ready for review & merge!

**Comment by ctb** [comment]
ready for review & merge @sourmash-bio/devs

**Comment by ccbaumler** [comment]
The addition of the `build` module tells the software to look through the pyproject.toml for the specific build artifacts in the file?

**Comment by ctb** [comment]
> The addition of the `build` module tells the software to look through the pyproject.toml for the specific build artifacts in the file?

see https://pypi.org/project/build/ and conversation here: https://github.com/sourmash-bio/sourmash/issues/2112#issuecomment-1179537987

this PR just adds the installation of `build` to more places where we need it in the release process.

**Review by ccbaumler — APPROVED** [review]
LGTM

**Comment by ctb** [comment]
thanks @ccbaumler !

**Pull request merged**
