### PR TITLE
[WIP] Use a Nodegraph for searching in internal nodes

### LINKED ISSUE #203: Convert query to BF before searching?
Currently `sbt_search` check for presence in the internal Bloom Filters for each hash in the query MinHash. What if we load the hashes in a BF first, and then do BF/BF comparisons instead?

(this is somewhat premature optimization, but since we are seeing bigger signatures with small `scaled` arguments it might be worth to try)

### PR DESCRIPTION
**Pull request by luizirber**
Updated version of #395, fixes #203

This builds up on #1137 and uses a Nodegraph for querying internal nodes. It actually passes the test currently failing in #1137, so I'm starting to think there is something fishy going on with `node.data.matches(mh)`...

## TODO:

- [ ] It is slower than the previous way, which is annoying. Might need to change how containment and similarity are calculated in Rust (can do popcnt over the bitsets, instead of building intersection and union)

## Checklist

- [ ] Is it mergeable?
- [ ] `make test` Did it pass the tests?
- [ ] `make coverage` Is the new code covered?
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
>I'm starting to think there is something fishy going on with `node.data.matches(mh)`...
oh no!

**Comment by ctb** [comment]
curious if the changes in https://github.com/dib-lab/sourmash/pull/1392 help or hurt this effort.

(I don't like all of the function/class names in that PR, but it does some nice code cleanup and consolidation so I plan to propose it for merge in a few weeks.)

**Comment by luizirber** [comment]
>> I'm starting to think there is something fishy going on with `node.data.matches(mh)`...
> oh no!

turns out I was doing `ng.containment(ng2)` wrong, oops!
(I was using `sum(len(hash_tables))` as denominator, which underestimated containment; the fix was to use `sum(set_bits)`, only considering the bits that are set in the nodegraph)

**Comment by luizirber** [comment]
Not focusing on SBTs anymore

**Pull request closed without merging**
