### PR TITLE
[MRG] Rework the `find` functionality for `Index` classes

### LINKED ISSUE #829: Upgrade `sourmash categorize` to take LCA databases as well as SBT.
sourmash categorize should be able to take an LCA database as well as an SBT.

There are a lot of other things we could do upgrade `categorize` as well; could brainstorm a little about what it is doing, should be doing, and could be doing.

### LINKED ISSUE #1377: Request that `Index` provide a location?
In #1373, I added a `location` attribute to SBTs. We have something similar in `LinearIndex` and `LCA_Database` already (`filename`), and could add it to `MultiIndex` in #1374 as well.

The idea would be to provide a programmatic identifier for the location from which a database was loaded. In an ideal world, this would be something that the `.load(...)` function for that `Index` class could understand, although I don't want to require that just yet as it seems restrictive for in-memory `Index` classes.

In the case where a location was not available or did not make sense, it would be left as `None`.

See [this comment on ZipFile](https://github.com/dib-lab/sourmash/pull/1349#issuecomment-787471774) for some thoughts on URL schemes to maybe use for this.

### LINKED ISSUE #1389: 'search --best-only' on SBTs only works for similarity, not for containment
Discovered by @bluegenes during code review in #1346. This should be fixable, but requires some thought.

See https://github.com/dib-lab/sourmash/pull/1346#pullrequestreview-610875993 for initial resolution (raise an error :) + tests.

### LINKED ISSUE #1454: `sourmash index` does not flatten the signatures when building an SBT
I've always assumed that sourmash index only stores flattened signatures, since there's no way to do an abundance-search on the SBT. I was wrong!

I guess I'm not clear on whether this is good, or bad; intentional, or not. Hence - issue!

```
% sourmash index xyz.sbt.zip tests/test-data/gather-abund/reads-s10-s11.sig

== This is sourmash version 4.0.1.dev21+gc49a8d84.d20210405. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

loading 1 files into SBT
loaded 1 sigs from 'tests/test-data/gather-abund/reads-s10-s11.sig'

loaded 1 sigs; saving SBT under "xyz.sbt.zip"
Finished saving nodes, now saving SBT index file.
Finished saving SBT index, available at /Users/t/dev/sourmash/xyz.sbt.zip

% sourmash sig describe xyz.sbt.zip

== This is sourmash version 4.0.1.dev21+gc49a8d84.d20210405. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

---reading from file 'xyz.sbt.zip'
signature filename: xyz.sbt.zip
signature: 1-1
source file: r3.fa
md5: 43e3b5d6f298a181e32d0244eac643a3
k=21 molecule=DNA num=0 scaled=1000 seed=42 track_abundance=1
size: 770
signature license: CC0

loaded 1 sigs from 'xyz.sbt.zip'
loaded 1 signatures total.
```

### PR DESCRIPTION
**Pull request by ctb**
"They who control `find` control the universe."

This PR implements a common `Index.find` generator function for Jaccard similarity and containment on `Index` classes.

This new generator function takes a `JaccardSearch` object and a query signature as inputs, and yields all signatures that meet the criteria.

The `JaccardSearch` object in `src/sourmash/search.py` is the workhorse for `find`; it scores potential matches (and can truncate searches) based on `query_size`, `intersection`, `subject_size`, and `union`, which is sufficient to calculate similarity, containment, and max_containment.

This provides some nice simplifications -
* `Index.search` and `Index.gather` can be implemented generically on top of `find`, and are now methods on the base `Index` class;
* this supports fast `prefetch` functionality on top of all of our `Index` subclasses (SBT and LCA as well), ref #1370 and #1371 and #1226;
* all of the janky SBT-specific search code in `sbtmh.py` is no longer needed;

Moreover,

* the logic around downsampling and database search is greatly simplified, and is now much more thoroughly tested;
* the logic for abundance searches is split off into a separate function, which seems appropriate given that it's largely unused and largely untested...;

The overall result is a pretty good code consolidation and simplification.

This PR also:
* splits `sourmash search` functionality into flat queries (uses new `search_fn` functionality, works on SBT and LCA too) and abund queries (only works on `LinearIndex`)
* fixes `sourmash categorize` to work with more than SBTs by using `load_file_as_index` for the database (#829)
* adds a `location` property to `Index` classes (https://github.com/dib-lab/sourmash/issues/1377)
* creates a `namedtuple` for results from `Index.search` and `Index.gather` that improves code readability;

Specifically, this PR:

Fixes #829 - `sourmash categorize` now takes all database types
Fixes https://github.com/dib-lab/sourmash/issues/1377 - provides a `location` property on `Index` objects
Fixes https://github.com/dib-lab/sourmash/issues/1389 - `--best-only` now works for similarity *and* containment
Fixes #1454 - `sourmash index` now flattens SBT leaves.

Larger thoughts:
* Over in #1454 the question is asked, can we reliably do 'flat' Jaccard searches to discover good candidates for abundance matches (e.g. angular similarity)? Maybe worth creating a new issue.
* This PR addresses @luizirber [comment](https://github.com/dib-lab/sourmash/pull/1371#issuecomment-797688963) that `Index.find` is probably the key thing to implement for `prefetch` (or at least that's how I reinterpreted his comment :).

## Questions and comments for reviewers

* One goal for this is to better support a prefetch linear pass search, #1226. I'm not clear on whether I've gotten the abstractions right in such a way that they can be used/optimized in Rust code. Comments please!
* the `search` and `gather` methods in the `Index` class, and the `find` functions in the various `Index` subclasses, are really the key changes in this PR.
* this breaks backwards compatibility for what I think is a bug (at the very least it is previously undocumented behavior :) - we allowed storage of abund signatures in SBTs, and `sourmash categorize` took advantage of this to return angular similarity calculations when the query signature had abundances. 
    * This is literally the only place in the code base where this was used, so... I disabled it. See "Larger thoughts", above, and check out #1454.
    * In terms of user notification, sourmash  now produces an appropriate error message requiring the user to specify `--ignore-abundance` explicitly, which should steer people in the right direction and minimize the impact of this.
* this breaks backwards compatibility for loading v1 and v2 SBT databases. I think this is correct. Briefly,
    * the old test code did containment searches on SBTs with num MinHashes in them, which is incorrect.
    * the new test code does a Jaccard search, and v1/v2 SBTs do not support `min_n_below`. This may be fixed by #1137, but I think it's out of scope for this PR :)
    * if we want to keep this working for the next release, then we would need to merge #1137 before the next release (or do something else, like hold this PR until #1137).
    * Also see #1397 - we can't easily create old version SBTs any more, it seems; in particular, we don't have any releases that create v1 and v2 SBTs!

## TODO items:
- [x] look into v1/v2 SBT breakage/tests in more detail.
- [x] fix docstring in `sbt.py` and `lca_db.py`
- [x] look into `test_sbt.py` lines 419 and 458, why are they not run!?
- [x] see @CTB note in `test_search.py`
- [x] look into commented out line in `test_sbt_categorize_ignore_abundance_2`
- [ ] create new "good first issue" to replace the tuple indices in results checking in test_index.py with the new `IndexSearchResult` namedtuple attributes.
- [x] fix up and test `categorize` code
- [x] write more better tests of sourmash gather with abundance signatures & save unassigned
- [x] double check multigather tests; look at save unassigned there, too.
- [x] look into removing categorize use of `LoadSingleSignature` https://github.com/dib-lab/sourmash/issues/1077
- [x] write tests for new `get_search_obj` function
- [x] clean up, document, and test all of the downsampling etc code in `find`
- [x] implement/test find_best code fixing https://github.com/dib-lab/sourmash/issues/1389
- [x] test num logic in minhash.py
- [x] implement unload_data

### CODE REVIEW

**Comment by ctb** [comment]
OK, this is converging - and all of the key tests are working, so it's down to code cleanup, documentation, and some testing additions.

### new design decision: splitting search with abund sketches vs search with flat sketches

The large majority of our tests (and use cases) have to do with searching flat signatures, i.e. using sketches created with `-p noabund`. This is also true for `gather`.

In addition, neither LCAs nor SBTs support storing or searching signatures with abundances.

So I've opted for splitting the `Index` functionality into `search`/`gather`, which both use Jaccard similarity/containment and work for all databases; and `search_abund`, which only works on `LinearIndex`.

- [ ] add tests for search_abund

**Comment by ctb** [comment]
note to self: Index classes now only need to define `find`, then `search` and `gather` can be used from base class.

**Comment by ctb** [comment]
note to self: another good first issue is to replace the tuple indices in results checking in test_index.py with the new `IndexSearchResult` namedtuple attributes.

**Comment by ctb** [comment]
note to self: `find` can be used with `prefetch` to enable queries that make use of Jaccard abundance.

**Comment by ctb** [comment]
Note: fixes https://github.com/dib-lab/sourmash/issues/1454, but at the cost of breaking backwards compat.

`sourmash categorize` now produces an appropriate error message requiring the user to specify `--ignore-abundance` explicitly, which should steer people in the right direction and minimize the impact of this.

**Comment by ctb** [comment]
This is ready for review @luizirber @bluegenes  ; there's one or two minor things to be done, but it's 99.9% done.

**Comment by ctb** [comment]
OK, I think this is done, provisionally.

**Comment by luizirber** [comment]
Review ongoing, but while I don't finish it: the gather implementation for SBTs became way slower, and memory consumption also went up:

image

**Comment by ctb** [comment]
yeesh! that's not good!

I wonder if `unload_data`'s default changed?

**Comment by ctb** [comment]
(there's no obvious algorithmic reason for the time or memory to go up)

**Comment by luizirber** [comment]
> (there's no obvious algorithmic reason for the time or memory to go up)

All set calculations are done in Python now:
https://github.com/dib-lab/sourmash/pull/1392/files#diff-796cf35ae8d09c8df495f82265c2593075e00b9d91f5fed92f3e17e47d155a16R421

While not _algorithmic_ different, it is a lot of memory copying to pull hashes out of Rust, create sets in Python, and then calculate...

**Comment by ctb** [comment]
> > (there's no obvious algorithmic reason for the time or memory to go up)
> 
> All set calculations are done in Python now:
> https://github.com/dib-lab/sourmash/pull/1392/files#diff-796cf35ae8d09c8df495f82265c2593075e00b9d91f5fed92f3e17e47d155a16R421
> 
> While not _algorithmic_ different, it is a lot of memory copying to pull hashes out of Rust, create sets in Python, and then calculate...

ahh! good point! and that's pretty easy to fix with `MinHash` code... I'll see if I can get it working using the Rust code.

**Comment by ctb** [comment]
(great job on finding that, I struggled to get that code (a) working and then (b) clean and (c) tested, so now it's time for (d) optimization 😂)

**Comment by luizirber** [comment]
> (great job on finding that, I struggled to get that code (a) working and then (b) clean and (c) tested, so now it's time for (d) optimization joy)

(that's the code I need to change for #1137 #1138 #1201 #1221, so...)

**Comment by ctb** [comment]
> (that's the code I need to change for #1137 #1138 #1201 #1221, so...)

image

**Comment by ctb** [comment]
> > > (there's no obvious algorithmic reason for the time or memory to go up)
> > 
> > 
> > All set calculations are done in Python now:
> > https://github.com/dib-lab/sourmash/pull/1392/files#diff-796cf35ae8d09c8df495f82265c2593075e00b9d91f5fed92f3e17e47d155a16R421
> > While not _algorithmic_ different, it is a lot of memory copying to pull hashes out of Rust, create sets in Python, and then calculate...
> 
> ahh! good point! and that's pretty easy to fix with `MinHash` code... I'll see if I can get it working using the Rust code.

https://github.com/dib-lab/sourmash/pull/1474 provides a `MinHash.intersection` implemented in Rust. Would be interested in benchmarks!

**Comment by ctb** [comment]
note to self: @bluegenes and I want to add a `match` argument to `JaccardSearch.collect(...)` so that we can ignore matches to specific signatures, either by identity or by name or by ...

this would enable https://github.com/dib-lab/sourmash/issues/985 and https://github.com/dib-lab/sourmash/issues/849 more generically.

Edit: added in https://github.com/dib-lab/sourmash/pull/1477

**Review by luizirber — APPROVED** [review]
This is already a large PR, and there are PRs merging more code into this, so I vote for merging now and rebasing the other ones.

Overall a nice cleanup of the codebase, no obvious performance regressions, and I think it mostly fits with future indices written in Rust.

**Pull request merged**
