### PR TITLE
[MRG] add picklists to selector protocol and provide initial `Index` support

### PR DESCRIPTION
**Pull request by ctb**
This PR adds picklists (#1587) into the selector protocol so that `Index.signatures(...)` and `Index.find(...)` both respect picklists, and also introduces it throughout the command-line interface.

In detail, this PR:
* adjusts `Index.select(...)` to support a `picklist` keyword argument and adds picklist support to the main `Index` subclasses;
* adds picklist support to `SBT.select(...)` and `LCA_Database.select(...)` as well;
* adds picklist support to `load_file_as_signatures(...)`
* refactors `sourmash sig extract` to pass its picklist into `load_file_as_signatures(...)`, rather than do ad hoc picklisting;
* adds `--picklist` support to `compare`, `gather`, `index`, `lca index`, `prefetch`, and `search`

Note, I decided against adding picklists to `lca summarize` and `lca classify` for now, since I think we may be end-of-life-ing LCA databases soon.

This does not implement any optimizations for picklist-intersected database searches yet, but they are coming - see #1590!

TODO:
- [x] add docs
- [x] verify that prefetch CSV can be used as a picklist
- [x] verify that 'index' with picklist == 'index' then 'search' with picklist

### CODE REVIEW

**Comment by ctb** [comment]
Ready for review @bluegenes.  There's a few minor issues to do with our test infrastructure that I'll deal with before considering merge, but the PR is feature complete ;)

**Comment by ctb** [comment]
ok, tests are actually passing now, too! Ready for review and maybe merge!

**Review by bluegenes — APPROVED** [review]
lgtm! looking forward to actually playing around with picklists soon :)

**Comment by ctb** [comment]
thank you!!

**Pull request merged**
