### PR TITLE
upgrade rocksdb to 0.22.0

### PR DESCRIPTION
**Pull request by mr-c**
Seeing if we can upgrade to the latest rocksdb safely.

### CODE REVIEW

**Comment by mr-c** [comment]
Ah, it would require bumping the minimum `rustc` version to 1.66

**Comment by luizirber** [comment]
> Ah, it would require bumping the minimum `rustc` version to 1.66

This is OK for us, we try to keep the MSRV compatible with what is available in Debian. What is the current Rust available in Debian? I usually check https://packages.debian.org/search?keywords=rustc but it is 503 now, [repology](https://repology.org/project/rust/versions) says `1.63` for `bookworm` and up to `1.82` for `trixie`?

**Comment by mr-c** [comment]
> > Ah, it would require bumping the minimum `rustc` version to 1.66
> 
> This is OK for us, we try to keep the MSRV compatible with what is available in Debian. What is the current Rust available in Debian? I usually check https://packages.debian.org/search?keywords=rustc but it is 503 now,

On a Debian system, you can run `rmadison rustc` (or any Debian package name) to see which versions are in the official archive.

> [repology](https://repology.org/project/rust/versions) says `1.63` for `bookworm` and up to `1.82` for `trixie`?

And repology is also a decent source, yes 👍🏻

https://packages.ubuntu.com/rustc

**Okay, shall I bump the MSRV and retry this PR?**

In Debian we are getting a weird error with the older `rocksdb` crate, so I wanted to see if the newer version broke anything for `sourmash`.

https://paste.debian.net/1334814/
> thread 'test_column_family_with_transactiondb' panicked at core/src/panicking.rs:221:5:
> unsafe precondition(s) violated: ptr::copy_nonoverlapping requires that both pointer arguments are aligned and non-null and the specified memory ranges do not overlap

**Review by luizirber — APPROVED** [review]
Thanks @mr-c!

**Pull request merged**
