### PR TITLE
[MRG] update lca summarize output to output total counts

### PR DESCRIPTION
**Pull request by ctb**
This PR adds a `total_counts` column to the CSV output of `sourmash lca summarize` per #1833.

Addresses most of https://github.com/sourmash-bio/sourmash/issues/1833.

### CODE REVIEW

**Comment by ctb** [comment]
Ready for review and merge @sourmash-bio/devs

**Review by mr-eyes — COMMENTED** [review]
In the test case output, the `counts` column equals to the `total_counts` I am not sure if this test case validates the `total_count` when it's different than the count.

**Comment by ctb** [comment]
> In the test case output, the `counts` column equals to the `total_counts` I am not sure if this test case validates the `total_count` when it's different than the count.

thanks @mr-eyes - added a new test!

**Review by mr-eyes — APPROVED** [review]
Looks great! Thank you.

**Comment by ctb** [comment]
thank *you*!

**Pull request merged**
