### PR TITLE
[MRG] cleanup and commenting of `test_index.py` tests.

### PR DESCRIPTION
**Pull request by ctb**
Note: PR into #1891. Review & merge after that one.

This PR does some cleanup and commenting on `tests/test_index.py`, as well as pyflakes-based cleaning of `src/sourmash/index/__init__.py`.

This is a pure commenting-and-docstring PR, no code changes.

### CODE REVIEW

**Comment by luizirber** [comment]
> as well as pyflakes-based cleaning

:open_mouth: you're using pyflakes?!?!?

**Comment by ctb** [comment]
> > as well as pyflakes-based cleaning
> 
> 😮 you're using pyflakes?!?!?

yes... is that surprising? or bad?

**Comment by luizirber** [comment]
> yes... is that surprising? or bad?

it's great, means that we might finally uncomment `flake8` from the [pre-commit checks](https://github.com/sourmash-bio/sourmash/blob/aef00366749aacde3dc1e505b1ee93db8109cff1/.pre-commit-config.yaml#L65) :upside_down_face:

(or at least run these things more frequently and reduce the mountain of warnings :see_no_evil: )

**Comment by ctb** [comment]
> > yes... is that surprising? or bad?
> 
> it's great, means that we might finally uncomment `flake8` from the [pre-commit checks](https://github.com/sourmash-bio/sourmash/blob/aef00366749aacde3dc1e505b1ee93db8109cff1/.pre-commit-config.yaml#L65) 🙃
> 
> (or at least run these things more frequently and reduce the mountain of warnings 🙈 )

sure - I can make that an issue. It'd be good to do it systematically across the code base; in the tests I have more tolerance for unused variables, but even there flakes found a number of shadowed tests - see #1863.

**Review by luizirber — APPROVED** [review]

**Pull request merged**
