### PR TITLE
[MRG] swap ValueError for SourmashCommandFailed

### PR DESCRIPTION
**Pull request by ctb**
I merged #1621 carelessly, and a few exceptions didn't get their names swizzled over properly.

Please review - thx! @sourmash-bio/devs

### CODE REVIEW

**Comment by ctb** [comment]
Ready for merge!

**Comment by ctb** [comment]
@keyabarve could you review this, please? I think you'll recognize the changes 😁

**Comment by keyabarve** [comment]
Sure!

**Review by keyabarve — COMMENTED** [review]
lgtm!

**Comment by ctb** [comment]
thanks!

**Pull request merged**
