### PR TITLE
Added seed to parameter strings #1732

### LINKED ISSUE #1732: add `seed` to param string docs
per https://github.com/sourmash-bio/sourmash/issues/1731, the [command line docs for sourmash sketch](https://sourmash.readthedocs.io/en/docs_4.0/sourmash-sketch.html) do not mention `seed`, which (based on inspecting the code) should work!

### PR DESCRIPTION
**Pull request by rialc13**
This PR adds 'seed' to parameter string in doc/sourmash-sketch.md as per #1732 . Fixes #1732 .

### CODE REVIEW

**Comment by rialc13** [comment]
Hi. I am new to this. @luizirber Can you please help me understand the issue? I am not able to figure it out.

**Comment by ctb** [comment]
> Hi. I am new to this. @luizirber Can you please help me understand the issue? I am not able to figure it out.

Everything looks good to me! I just approved GitHub Actions to run on this PR.

**Comment by ctb** [comment]
Everything looks good to me - docs built from this PR are [here](https://sourmash--2836.org.readthedocs.build/en/2836/sourmash-sketch.html), if you want to see for yourselves!

@rialc13 would you like me to merge? Or do you have more changes in mind?

**Review by ctb — APPROVED** [review]

**Comment by ctb** [comment]
merging when tests pass

**Review by ctb — APPROVED** [review]

**Pull request merged**
