### PR TITLE
Add ORCID to checklist

### LINKED ISSUE #674: Add ORCID to checklist
We are adding PR contributors to the JOSS paper, and we need ORCID for that.

Add another item to the PR checklist asking for an ORCID (if new contributor), and also pointing to instructions on how to set up a new ORCID account.

### PR DESCRIPTION
**Pull request by keyabarve**
Fix #674 

## Checklist

- [ ] Is it mergeable?
- [ ] `make test` Did it pass the tests?
- [ ] `make coverage` Is the new code covered?
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by keyabarve** [comment]
Please review @ctb @luizirber

**Comment by ctb** [comment]
thanks, keya!

suggest changing language to "please note your ORCID in the comments. If you don't have one, you can register for one here."

also, suggest you note your ORCID in the comments 😁

**Comment by keyabarve** [comment]
@ctb @luizirber 
I made the necessary changes. Please review.

**Comment by ctb** [comment]
hi @keyabarve thanks! Change requests:

* first, the link in the markdown doesn't render. You need to move the period after ] to the end of the sentence in this text `[here].(https://orcid.org/register)`
* second, what's your ORCID? please register for one and when you get it, put it in the comments here :)

thanks!

**Comment by ctb** [comment]
oh, and after you make the requested change, please update your branch from `latest` so that it includes the latest changes on our main branch (you can use the `Update branch` button, or you can do `git pull origin latest; git push` on the command line).

**Comment by keyabarve** [comment]
The link to my ORCID is: https://orcid.org/0000-0003-3241-2117
I will make the necessary changes and commit them. I'm not sure about how to update the branch. Could you provide some more clarification?

**Comment by ctb** [comment]
hi @keyabarve, there is an "Update branch" button on this pull request; scroll to the bottom, look to the right. If you use that, you need to also do `git pull origin` when `git status` shows that you are on your `ORCIDchecklist` branch.

That will do the equivalent of:

```
git pull origin latest
git push origin ORCIDchecklist
```

on your working computer.

**Comment by keyabarve** [comment]
On the command line of my computer, I did:
```git pull origin latest```
```git push origin ORCIDchecklist```
Please review.

**Comment by ctb** [comment]
it is updated, yay!

however, the markdown issue mentioned [above](https://github.com/dib-lab/sourmash/pull/1405#issuecomment-808744643) still needs a fix.

thanks!

**Comment by keyabarve** [comment]
I have fixed the issue! 
Please review.
Thanks!

**Review by ctb — APPROVED** [review]

**Comment by ctb** [comment]
thanks! merging now!

**Pull request merged**
