### PR TITLE
MRG: fix many minor documentation nits

### PR DESCRIPTION
**Pull request by ctb**
Follow-up to #2184 with minor corrections.

### CODE REVIEW

**Comment by ctb** [comment]
@ccbaumler mind taking a quick look at the changes? thx!

**Comment by taylorreiter** [comment]
Had a chance to look again -- love the simplified nav bar on the left. I can't find the generic dev docs anymore tho, can those be added back in or am I missing some context?

**Comment by ctb** [comment]
> Had a chance to look again -- love the simplified nav bar on the left. I can't find the generic dev docs anymore tho, can those be added back in or am I missing some context?

Working on that over in #2811 - not quite ready yet, but mostly updated the structure. Comments welcome!

I may take your "had a chance to look at this PR" as an implicit endorsement of merging it, depending on whether I get any other feedback today ;)

**Review by taylorreiter — APPROVED** [review]
now it's explicit :)

**Pull request merged**
