### PR TITLE
[MRG] Dev install

### PR DESCRIPTION
**Pull request by bluegenes**
@keyabarve can you verify this works for you?

There are other dev instructions that need updating, but this minor fix enables easy conda development.

### CODE REVIEW

**Comment by keyabarve** [comment]
Yes, this worked for me and the tests started running correctly.

**Comment by mr-eyes** [comment]
> Yes, this worked for me and the tests started running correctly.

@keyabarve I believe Tessa means if the command proposed in this PR was the fix for your problem.

**Comment by keyabarve** [comment]
Yes, I ran this command: `pip install -e ".[test]"` and the tests started running for me. But before I ran this command, I also ran `pip install -r requirements.txt`.
So I ran the commands in the following order:
1. `pip install -r requirements.txt`
2. `pip install -e ".[test]"`

After this, I ran `pytest` and all the tests ran for me.

**Comment by ctb** [comment]
maybe relevant issues:

https://github.com/sourmash-bio/sourmash/issues/1482
https://github.com/sourmash-bio/sourmash/issues/1375

and relevant PR:

https://github.com/sourmash-bio/sourmash/pull/1522

**Pull request closed without merging**
