### PR TITLE
[MRG] Revert bad merge into stable.

### PR DESCRIPTION
**Pull request by ctb**
Revert an inadvertent merge/push to `stable` of #1308.

## Checklist

- [ ] Is it mergeable?
- [ ] `make test` Did it pass the tests?
- [ ] `make coverage` Is the new code covered?
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by luizirber** [comment]
Did this remove too much? 743cd94f7043ae792172e968ce71ebef35bda28e should stay, no?

**Comment by ctb** [comment]
argh argh argh.

**Comment by ctb** [comment]
ok, fixed I think.

**Review by luizirber — APPROVED** [review]

**Comment by luizirber** [comment]
I rebased and dropped the commits in `stable`, so this PR is not needed anymore.

**Pull request closed without merging**
