### PR TITLE
1798: implementation of function to test if cardinality estimate is accurate wrt scale size

### LINKED ISSUE #1798: debiasing FracMinHash - plans and progress
In re this paper,

[Debiasing FracMinHash and deriving confidence intervals for mutation rates across a wide range of evolutionary distances](https://www.biorxiv.org/content/10.1101/2022.01.11.475870v2)

the question arose, is this being implemented in sourmash? [see Twitter thread](https://twitter.com/KlaasMensaert/status/1483001071614275585) and @luizirber draft PR https://github.com/sourmash-bio/sourmash/pull/1270.

quoth @dkoslicki -
>Planned. Should be really straightforward to implement, as sourmash already had some cardinality estimators built in, iirc

and @luizirber -
> Plan was to avoid changing the sig format because it could be calculated from the MH data, instead of building a HLL during sketching and saving it too (or just the # of unique k-mers from the HLL)

---

also for grins, check out this paper:

[The minimizer Jaccard estimator is biased and inconsistent](https://www.biorxiv.org/content/10.1101/2022.01.14.476226v1)

### PR DESCRIPTION
**Pull request by dkoslicki**
Fixes #1798 in part: implements a function that tells you if your sketch size is large enough in order to be able to trust `num_hashes * scale` as an estimate of the number of distinct k-mers

This is placed in the `Utils` folder since @bluegenes will likely want to mover it elsewhere. Tests are in the script itself: run in main.

Note that this does *not* fully fix #1798 since we still need to be sure the de-biasing term is included. A future PR will address this. 

If you are a new contributor, please provide
My ORCID: [0000-0002-0640-954X](https://orcid.org/0000-0002-0640-954X).

### CODE REVIEW

**Comment by bluegenes** [comment]
Thanks @dkoslicki!! Quick question -- how does `np.floor` impact the `set_size` compared with just doing `num_hashes * scaled`?

**Comment by dkoslicki** [comment]
@bluegenes It shouldn't impact things at all. As I understand it, sourmash uses the denominator of the fraction (so 100 means 1/100th of the size of the original set), whereas I use the actual fraction (so 1/100). My way can lead to non-int estimates of set sizes (as can the sourmash approach, if it doesn't enforce `int(scale)==scale`), so that's to make sure it doesn't happen.

**Comment by bluegenes** [comment]
ah, makes sense -- thanks!

**Comment by bluegenes** [comment]
tagging @ctb as requested -- cardinality estimate accuracy eqns (🎉 !)

**Comment by ctb** [comment]
hi @bluegenes I kind of like having these in utils as well as in the running code base as in https://github.com/sourmash-bio/sourmash/pull/2032#issuecomment-1117988106. So I'm good for merge :).

**Review by bluegenes — APPROVED** [review]
lgtm, thanks @dkoslicki!

**Pull request merged**
