### PR TITLE
[MRG] Divide non-DNA MinHash ksize by 3 for external consumption.

### LINKED ISSUE #1271: adjust protein k-mer sizes for sourmash sketch?
@bluegenes has been working steadily on protein hashing, and a couple of times we have talked about what to do about protein k-mer sizes, which are currently set by specifying the size of the DNA k-mer from which the protein would have come. This is super confusing 

tl;dr for the next major release of sourmash, I'd like to suggest changing the command line options (`sourmash sketch protein`/`translate` and `sourmash compute`) to use the "true" protein k-mer size (so, 1/3 the current). I'd probably also suggest changing `sourmash sig describe` to output the 1/3.

Internals would not be changed at all, so there would be no need to confront the horror of signature format changes, internal class parameters, etc.

I'd like to add this for 4.0.

The downsides would be a substantial potential for user confusion, but my theory is that right now no one except sourmash devs is using sourmash protein k-mers, because we haven't really explored them in any public forum and people don't know what the opportunities and challenges of using them are!

As an alternative, we can avoid doing this now, and try to do changes to the CLI, Python & Rust internals, and also the signature format for 5.0, which I expect to include a lot of protein k-mer features and databases and...

thoughts @luizirber @bluegenes?

### PR DESCRIPTION
**Pull request by ctb**
This is a "light touch" fix to #1271, which makes it so that the entire Python (and CLI) layer of sourmash does protein/hp/dayhoff ksizes correctly: DNA k-mer sizes are the same, protein k-mer sizes are the lengths of the actual amino acid k-mers being used, and translated DNA k-mers are translated into the correct protein k-mer size.

This PR changes almost everything on the command-line and Python API side to match this - in particular, command line selectors are now different.
**The one exception is `sourmash compute` which still uses the "old" meaning of ksize for backwards compatibility reasons.**

No changes apply to existing signature or database formats, so this is forwards and backwards compatible with 3.5!

The key changes are in the `MinHash` wrapper class in `src/sourmash/minhash.py`:
* before passing ksize into the Rust layer, the constructor multiples the ksize by 3 for non-DNA minhashes.
* when retrieving ksize from the Rust layer, the `ksize` property divides the ksize by 3 for non-DNA minhashes.

Along the way, I also had to fix the LCA database to save/load its database correctly, with the adjusted ksize for non-DNA databases.

Most of the rest of the changes are minor fixes to command-line parameters or output, except for -
* I remove the code to test bug #781, because those signatures are no longer valid (protein ksize not divisible by 3)
* I include #1019 to require `sourmash compute` ksizes for non-DNA signatures to be multiples of 3.

Fixes #1271.
Includes #1019 

TODO:
- [x] include deprecation warning for `sourmash compute` for 5.0 removal
- XXX document differing behavior of compute and sketch - will be done in https://github.com/dib-lab/sourmash/pull/1283
- XXX add to migration guide https://github.com/dib-lab/sourmash/issues/1069 - will be done in https://github.com/dib-lab/sourmash/pull/1283
- [x] create issue for removing `sourmash compute` in 5.0

## Checklist

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make coverage` Is the new code covered?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
ready for review @luizirber @bluegenes

**Comment by luizirber** [comment]
I'll leave the `divide by 3` comments to @bluegenes (since she uses it =])

> The key changes are in the `MinHash` wrapper class in `src/sourmash/minhash.py`:
>  * before passing ksize into the Rust layer, the constructor multiples the ksize by 3 for non-DNA minhashes.
>  * when retrieving ksize from the Rust layer, the `ksize` property divides the ksize by 3 for non-DNA minhashes.

Should these be moved into Rust, then? (not asking you to do it, but since both operations are 'fixing' what is being sent/retrieved from the Rust layer...)

**Comment by ctb** [comment]
> > The key changes are in the `MinHash` wrapper class in `src/sourmash/minhash.py`:
> > 
> > * before passing ksize into the Rust layer, the constructor multiples the ksize by 3 for non-DNA minhashes.
> > * when retrieving ksize from the Rust layer, the `ksize` property divides the ksize by 3 for non-DNA minhashes.
> 
> Should these be moved into Rust, then? (not asking you to do it, but since both operations are 'fixing' what is being sent/retrieved from the Rust layer...)

Before I wrote this PR, I would have said "no" or "maybe" to moving it to the Rust layer. Now I'm on "maybe" or "yes" - it's not that big a change, in practice! (I'm impressed with how clean it turned out to be.)

**Comment by taylorreiter** [comment]
No comment on mv to rust layer, but

> before passing ksize into the Rust layer, the constructor multiples the ksize by 3 for non-DNA minhashes.
> when retrieving ksize from the Rust layer, the ksize property divides the ksize by 3 for non-DNA minhashes.

This is wonderful. If I'm in protein space and request k = 9, I want sourmash to give me **9 amino acids**. It's so so confusing when that is not the case. If @bluegenes has a different preference/opinion, hers is probably better than mine :) 

> **The one exception is sourmash compute which still uses the "old" meaning of ksize for backwards compatibility reasons.**

So we still have to do the weird 3 thing...but only in part of sourmash?

**Comment by ctb** [comment]
> > **The one exception is sourmash compute which still uses the "old" meaning of ksize for backwards compatibility reasons.**
> 
> So we still have to do the weird 3 thing...but only in part of sourmash?

yes, and that part is getting deprecated in 4.0 and removed in 5.0.

The reason to keep it working the same is so that we don't mess up people who are using 2.x and 3.x `sourmash compute` terminology in their workflows. An alternative would be to explicitly "break" protein calculations via `sourmash compute` and require people to use `sourmash sketch` - but that seems ungentle.

**Comment by bluegenes** [comment]
As I understand it:

- `sourmash sketch` and the python api will now take the direct protein ksize
- `sourmash compute` remains as-is, which is direct protein ksize *3
- internals all use DNA ksizes, no matter the input alphabets.

I'm 100% on board with these! I do think that a deprecation warning for `compute` and/or detailed help message for how `sketch` differs from `compute` might be helpful for `4.0`, though as you point out, we're likely the only ones using protein functionality.

This PR gets close to not needing to worry about protein ksize conversion! 

Main question -- What is happening with selectors? It's not intuitive to sketch at `protein k=10` but need to use `k=30` to select that sketch from a sigfile, particularly given the fact that we're pushing towards _no manual ksize corrections_ in sketch / python api.

**Comment by bluegenes** [comment]
> This is wonderful. If I'm in protein space and request k = 9, I want sourmash to give me **9 amino acids**. It's so so confusing when that is not the case. If @bluegenes has a different preference/opinion, hers is probably better than mine :)

`compute` has some other negatives for protein sketches, mainly that it's difficult to use specific ksizes for the different protein alphabets if you're sketching all at once. So I've entirely abandoned `compute` in favor of `sketch`, so have no issue with `compute` remaining as-is 🙂 🤷‍♀️

**Comment by ctb** [comment]
> As I understand it:
> 
>     * `sourmash sketch` and the python api will now take the direct protein ksize

yes!
 
>     * `sourmash compute` remains as-is, which is direct protein ksize *3

yes!
 
>     * internals all use DNA ksizes, no matter the input alphabets.

actually, no - Python internals use "correct" ksizes!!

> I'm 100% on board with these! I do think that a deprecation warning for `compute` and/or detailed help message for how `sketch` differs from `compute` might be helpful for `4.0`, though as you point out, we're likely the only ones using protein functionality.

absolutely. I'm working on that in documentation PRs and will also put in a deprecation here (and think about backporting it).
 
> This PR gets close to not needing to worry about protein ksize conversion!

I think, for you, you would simply never need to worry about it, yes! Rust users might, but that's an army of 1.6, for now (standard 1.5x multiplier for Luiz, plus 0.1 for me).
 
> Main question -- What is happening with selectors? It's not intuitive to sketch at `protein k=10` but need to use `k=30` to select that sketch from a sigfile, particularly given the fact that we're pushing towards _no manual ksize corrections_ in sketch / python api.

Selectors work with the divide-by-3 number, so it's all consistent. The only odd-command-out is `compute`.

I will take all of this as license to proceed towards making this a merge-able PR - thanks, all!

**Comment by ctb** [comment]
Ready for review and merge!

**Review by luizirber — APPROVED** [review]

**Comment by luizirber** [comment]
(I'll do a new PR for moving the checks into Rust, but easier to have this one merged and then use the tests to move the code around =])

**Comment by ctb** [comment]
yay w00t!

**Pull request merged**
