### PR TITLE
replace notify format usage with f-strings instead (#1409) (#1418)  

### LINKED ISSUE #1418: update call to `notify` in `src/sourmash/search.py` with f-strings
(a specific issue for the general case in https://github.com/dib-lab/sourmash/issues/1409)

in `src/sourmash/search.py`, there is a call to `notify` in the function `gather_databases` that uses `{}` instead of f-strings. please update!

this issue is for https://github.com/itsabhianant

### PR DESCRIPTION
**Pull request by noturshek**
Fixes #1418 
Ref #1409

### CODE REVIEW

**Comment by ctb** [comment]
hi @itsabhianant this looks good - should I review?

**Comment by ctb** [comment]
(you should "update branch", too, since we've merged something into latest since you started this)

**Comment by noturshek** [comment]
Hi @ctb,

I have updated the branch as per your instructions.

**Comment by ctb** [comment]
ok! I'll wait for the tests to pass and then merge it.

request - could you edit the top comment to say something like,

```
Fixes https://github.com/dib-lab/sourmash/issues/1418
Ref #1409
```

so that the issues are linked? You did put the relevant issue numbers in the title of the pull request, but GitHub doesn't interlink the issues based on things in the title, it seems. Thanks!

**Comment by noturshek** [comment]
Hi @ctb,

I don't know how to that as I am new to GitHub. I searched for it on the web but that didn't help. Could you please help me more briefly? Should we add links in the same way we do for README.md?

**Comment by ctb** [comment]
sure! I saw you changed the title, but I think the old title was mostly fine so you should change that back ;).

to edit the PR description, go to the '...' in the upper right of the first text box, just above "Checklist", and select "Edit".

**Comment by noturshek** [comment]
I updated the top comment as per your instructions @ctb . Is it fine or there are more changes to be made? Thanks for the help.

**Comment by ctb** [comment]
hi @itsabhianant, if you use the format here,
```
Fixes https://github.com/dib-lab/sourmash/issues/1418
Ref #1409
```
it will automatically close #1418 when this is merged, which is the preferred behavior. As it is, it properly references the two issues but won't close #1418.

(note you can use
```
Fixes #1418
Ref #1409 
```
too, github understands both the full link to the issue and just the issue number)

**Comment by noturshek** [comment]
Hi @ctb,

I am getting an error while checking  that displays:
`There was a problem with Read the Docs while building your documentation`. 
I don't know what to do now...

**Comment by ctb** [comment]
no worries, that's not your fault! it's just a sporadic problem with RTD.

**Comment by noturshek** [comment]
Oh, thanks...
I think the checks have completed if we are to ignore the docs issue.

**Comment by ctb** [comment]
yep - can you please update the comment at the top, tho, per https://github.com/dib-lab/sourmash/pull/1422#issuecomment-810284384? That way the relevant issue will be closed when I merge.

**Comment by ctb** [comment]
(you don't want the parantheses around the issue numbers. to see that you've got it right, look at the "linked issues" on the right where it says "Successfully merging this pull request may close these issues." Right now, it says "None yet." It should mention #1418)

**Review by ctb — APPROVED** [review]

**Comment by noturshek** [comment]
I have done that now it says:
`This pull request closes issue #1418`


Thanks for all the help sir. I learned a lot from you.

**Comment by ctb** [comment]
Thank you for your contribution! If you would like to be listed as a contributor in future publications, we will need your ORCID; you can get one [here](https://orcid.org/register) if you don't have one already.

**Comment by ctb** [comment]
> I have done that now it says:
> `This pull request closes issue #1418`
> 
> Thanks for all the help sir. I learned a lot from you.

thank YOU!

if you are interested in trying out another issue, I'd suggest looking at one that involves editing/updating some test code. I can tag you in on two or three if you are interested. But no worries if not!

**Comment by noturshek** [comment]
where should I give my ORCID?

**Comment by ctb** [comment]
On Tue, Mar 30, 2021 at 07:49:57AM -0700, Abhishek Anant wrote:
> where should I give my ORCID?

please just put it in a comment on this pull request. thanks!

**Comment by noturshek** [comment]
Hi @ctb,
This is my ORCID id:

 [ORCID](https://orcid.org/0000-0002-5751-2010)

**Comment by noturshek** [comment]
> > I have done that now it says:
> > `This pull request closes issue #1418`
> > Thanks for all the help sir. I learned a lot from you.
> 
> thank YOU!
> 
> if you are interested in trying out another issue, I'd suggest looking at one that involves editing/updating some test code. I can tag you in on two or three if you are interested. But no worries if not!

Yes, I would love to work on other issues. Please do tag me for editing/updating some test code.

**Pull request merged**
