### PR TITLE
[MRG] fix sourmash sig cat on empty input

### PR DESCRIPTION
**Pull request by bryshalm**
This PR fixes the sig cat function's behavior on non-existent files and adds a test case. 

* made test for cat function in n_loader
* Fixes issue #1411
*  moved the n_loader command

https://orcid.org/0000-0002-8159-5127

### CODE REVIEW

**Comment by ctb** [comment]
ok, so this looks good! the test you have is sufficient to trigger the error (had you not fixed it). The two things I would suggest by way of code changes are -

* remove empty line 1600 and trailing whitespace lines since they're just unnecessary
* (maybe) add an assertion to check that the output is correctly saying something about having loaded 0 signatures. You can use something like this:

```
assert 'expected output' in c.last_result.err
```

where you replace 'expected output' with some of the text that is output by `sig cat empty-dir`. This makes sure that the message you're getting from running that command is the expected one.

**Comment by HTML-CODDER** [comment]
Conflicting files
src/sourmash/sig/__main__.py
tests/test_cmd_signature.py

**Review by HTML-CODDER — COMMENTED** [review]
Conflicting files
src/sourmash/sig/__main__.py
tests/test_cmd_signature.py

**Comment by ctb** [comment]
hi @bryshalm, if you want to continue working on this PR in order to get it to be merged, here's a short list of things to do -

first, please update the pull request title to something like "[WIP] fix `sourmash sig cat` on empty input"

second, update the description to -
* remove "Please replace this text with:"
* change "an adds" to "and adds"
* change the spacing in "Fixes issue # 1411" so that there's no space between the # and the 1411. This is a requirement for github to pick up the connection between this PR and issue #1411.

third, you'll need to fix the code - there's a Python syntax error in `src/sourmash/sig/__main__.py` due to an incorrect indentation. I can't see anything else that needs to be fixed but something might pop up after the first problem is fixed!

fourth, once all of the tests pass, update from latest by doing:
```
git pull origin latest
git push
```

fifth, change the title from [WIP] to [MRG]. "WIP" stands for work-in-progress, while "MRG" stands for "please merge" :).

sixth, ask for a review! (then respond to any issues raised during the review ;)

once that's all done, and this PR is merged, the original issue #1411 will be closed automatically.

**Comment by bryshalm** [comment]
how do I run python on a single file, such as just on __main__.py

**Comment by ctb** [comment]
On Sun, Jun 13, 2021 at 04:40:43PM -0700, bryshalm wrote:
> how do I run python on a single file, such as just on __main__.py

if it's within the sourmash Python package source code, which is
under src/sourmash/, then you have to run an import statement in Python:

import sourmash.sig.__main__

and then you can do

sourmash.sig.__main__.function_name()

to run the function function_name in that file.

what are you trying to do? There may be more specific advice I can give...

best,
--titus

**Comment by bryshalm** [comment]
Im still trying to find the error in the  __main__,py file

**Comment by ctb** [comment]
> Im still trying to find the error in the **main**,py file

ahh! if it's a parsing error, then you don't need to run anything in the file, just ask Python to parse it --

```
python src/sourmash/sig/__main__.py
```
should work.

**Comment by bryshalm** [comment]
Im getting the error message for line 10 "import sourmash"
No module named 'sourmash'

**Comment by ctb** [comment]
right - you can't actually _run_ the code that way, I'm afraid. But if it gets to that point, then the parse error has been fixed! Which was your original block to running the code :). So huzzah!

To run the code in situ, so to speak, you either need to (1) figure out what command-line function runs it, or (2) run the test(s) that execute it, or (my least favorite approach) (3) write a little script to run it yourself. This is because this code is part of the larger sourmash package and there's a lot of stuff in there that needs to imported and so on, so most parts of sourmash can't be run in isolation.

For (1), I seem to recall that something like this (at the command line) will work:

```
mkdir /tmp/empty-dir
sourmash sig cat /tmp/empty-dir
```

For (2), you could run
```
py.test tests -k <test_name>
```
where you replace `test_name` with something else,  _but_ you have a bit of a problem in that your test name appears to be a duplicate of an existing test name, and isn't being run. So you need to change the name from `test_import_mash_csv_to_sig` to something else - maybe `test_sig_cat_empty`?

For (3), I wouldn't recommend it, because you have (1) and (2) options that are easier.

Last but not least, it is concerning that `import sourmash` isn't working! Make sure you're running from inside your sourmash development environment (presumably a conda environment?) where you've done a `pip install -e .` at some point to install sourmash in editable/developer mode.

**Pull request closed without merging**
