### PR TITLE
[MRG] Adding cANI Rust implementation to PR #2943

### PR DESCRIPTION
**Pull request by mr-eyes**
# Rust implementation for ANI estimation

## Usage example:

```Rust

use crate::c_ani::containment_to_distance;

fn main() {
    let containment = 0.1;
    let ksize = 31;
    let scaled = 1000; // u64
    let n_unique_kmers = 1000;
    let sequence_len_bp = n_unique_kmers * scaled;
    let confidence = Some(0.95);
    let estimate_ci = Some(true);
    let prob_threshold = Some(1e-3);

    let result = containment_to_distance(
        containment,
        ksize,
        scaled,
        Some(n_unique_kmers),
        Some(sequence_len_bp),
        confidence,
        estimate_ci,
        prob_threshold,
    );


    match result {
        Ok(ci_result) => {
            let ani_result = 1.0 - ci_result.point_estimate;
            println!("ANI: {}", ani_result);
        }

        Err(e) => println!("Error occurred: {:?}", e),
    }
}
```

### CODE REVIEW

**Comment by bluegenes** [comment]
hi @mr-eyes if you change the branch to 'use-upd-gatheresult' i can go ahead and merge into my PR.

cheers for setting up - this ensures you get credit for your contributions :)

**Comment by mr-eyes** [comment]
> hi @mr-eyes if you change the branch to 'use-upd-gatheresult' i can go ahead and merge into my PR.
> 
> cheers for setting up - this ensures you get credit for your contributions :)

`upd-gatherresult` is now the base. Thank you!

**Review by bluegenes — APPROVED** [review]
thx!

**Comment by mr-eyes** [comment]
> thx!

You are most welcome!

**Pull request merged**
