### PR TITLE
[MRG] refactor `ZipFileLinearCollection` and `SaveSignatures_ZipFile` to use `ZipStorage`

### LINKED ISSUE #1441: refactor `ZipFileLinearIndex` to use `ZipStorage`
per https://github.com/dib-lab/sourmash/pull/1349#issuecomment-786920723

### PR DESCRIPTION
**Pull request by ctb**
This refactors `ZipFileLinearCollection` (reading) and `SaveSignatures_ZipFile` (creation) to use `ZipStorage` underneath, per https://github.com/sourmash-bio/sourmash/issues/1441.

Fixes #1441.

In detail, this PR:
* in `index.py`, replaces most direct access to files via `ZipFileLinearIndex.zf` (a `zipfile.ZipFile` object) with access via `sbt_storage.ZipStorage`;
* in `sourmash_args.py`, changes `SaveSignatures_ZipFile` to use `ZipStorage` underneath;
* we also extend `SaveSignatures_ZipFile` to append in situations where there is an existing zipfile + manifest;
* updates `sbt_storage.py:ZipStorage` to play more nicely with others - basically, a few new situations are encountered so we upgrade code accordingly;
* fixes a bug in `manifest.py` where `with_abundance` was incorrectly specified to be an integer - turns out that `int` works on a boolean `False`, but not a string `'False'` ;)
* updates and adds tests for new behaviors.

## Notes

This is a mostly-clean PR, with one exception - in `ZipFileLinearIndex`, we have to break `Storage` encapsulation and go directly to the zipfile to get a list of all files, in cases where there is no manifest. (Listing all files is not an option supported through the current `Storage` interface.) There are two options for fixing this -
   1. provide a way to list all (relevant) files in a Storage. It's not clear to me that this is a good idea, because a Storage may contain many files and many signatures.
   2. require manifests when using zipfile collections. This seems fine to me, but would (I think) require a 5.0 release.

Ultimately I think we will probably want to implement both, but not today :)

(In this PR, we _do_ require manifests in order to append signatures to an existing zipfile, but they are not required to _read_ from an existing zipfile.)

TODO:
- [x] test on some wonky, hand-constructed .zip files

### CODE REVIEW

**Comment by ctb** [comment]
@luizirber this is another PR you can look at; it doesn't have a lot of extraneous picklist and manifest stuff in it.

**Comment by ctb** [comment]
note to self: I might use this, or a related PR, to write some simple tests demonstrating `FSStorage` and `ZipStorage` as encouragement and partial documentation in support of #1752.

**Comment by ctb** [comment]
&lt;sigh&gt; another side note to myself, if we are trying to add to an existing zip file without a manifest, we need to fail here.

**Comment by ctb** [comment]
Ready for review @mr-eyes @luizirber!

**Comment by mr-eyes** [comment]
> Ready for review @mr-eyes @luizirber!

TFTM, I'm on it.

**Review by mr-eyes — APPROVED** [review]
LGTM!

**Pull request merged**
