### PR TITLE
MRG: use correct denominator in f_unique_to_query

### LINKED ISSUE #3137: Erroneous `f_unique_to_query` calculation in Rust code.
It looks like #2943 introduced a subtly broken calculation that uses the _current_ size of the query metagenome as the denominator for the `f_unique_to_query` calculation:

https://github.com/sourmash-bio/sourmash/blob/472d4e518bdbf039a8115bac87e60c9710cc2bd3/src/core/src/index/mod.rs#L235

In order to match the Python version, this should use the _original_ size of the query metagenome:

https://github.com/sourmash-bio/sourmash/blob/472d4e518bdbf039a8115bac87e60c9710cc2bd3/src/sourmash/search.py#L586

Discovered over in https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/318 when trying to debug discrepancies there ;)

### PR DESCRIPTION
**Pull request by ctb**
This PR fixes an issue introduced in #2943 where we introduced a subtly broken calculation that uses the _current_ size of the query metagenome as the denominator for the `f_unique_to_query` calculation.

Fixes https://github.com/sourmash-bio/sourmash/issues/3137

This PR also adds some commented-out test code that demonstrates https://github.com/sourmash-bio/sourmash/issues/3139 / https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/322. That's something I haven't been able to debug, so I'd suggest fixing that independently - I'd rather fix _a_ problem _now_, rather than waiting until we can fix _multiple_ problems at some later indeterminate time :).

## Notes

- [x] do we need to fix same problem in `linear.rs`? or just rename things per #3137?
- [x] we should add some tests for this

### CODE REVIEW

**Comment by bluegenes** [comment]
this change looks good. There is a test for the `calculate_gather_stats` function in the same file, but it doesn't have a query subtraction (just the initial calculation), so it doesn't reveal the issue fixed here.

I didn't originally realize - the revindex tests are here: https://github.com/sourmash-bio/sourmash/blob/fe4790f4828e39104141c895768261ed7cf411a1/src/core/src/index/revindex/mod.rs#L446

that would be a good spot to add tests

**Comment by ctb** [comment]
I did not know this: you have to specifically run the tests with `cargo test --features branchwater` or maybe `cargo test-all-features` in order to run the revindex tests!

(Our github actions does the right thing, I think. I just was struggling to get `cargo test` to fail ;)

**Comment by bluegenes** [comment]
> I did not know this: you have to specifically run the tests with `cargo test --feature branchwater` or maybe `cargo test-all-features` in order to run the revindex tests!

This confused me at first too + I regularly need to remind myself of cargo testing syntax. Do we have any sourmash rust dev docs yet?

**Comment by ctb** [comment]
the code in `linear.rs` doesn't seem to get run at all by the tests, and in any case doesn't calculate most of the stats. So I think we can safely ignore it. Before merging this, I'll make sure there's an appropriate issue update elsewhere (either a new issue, or updating an existing issue, gotta go check to figure out which is appropriate.)

**Comment by ctb** [comment]
note that when I started adding tests, I got problematic results per https://github.com/sourmash-bio/sourmash/issues/3139 / https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/322. 

The current tests _do_ check the denominator issue in #3137 so I think we should merge it and leave #3139 to another PR. Let me know if you disagree @bluegenes !

**Comment by ctb** [comment]
Ready for review & (assuming tests pass) merge!

**Review by bluegenes — APPROVED** [review]
lgtm!

**Pull request merged**
