### PR TITLE
MRG: update version of screed to >= 1.1,<2

### LINKED ISSUE #2394: update sourmash requirements for screed >= 1.1

### PR DESCRIPTION
**Pull request by ctb**
Fixes https://github.com/sourmash-bio/sourmash/issues/2394.

The main update in screed from 1.0.5 to 1.1 was https://github.com/dib-lab/screed/pull/90, which closes an unclosed file handle.

This PR also puts an upper bound on the screed version.

### CODE REVIEW

**Comment by luizirber** [comment]
For nix is likely not finding the new screed version due to https://github.com/sourmash-bio/sourmash/blob/1c8b1659d4f52901dee65360383e814ec7d6ccc5/flake.nix#L30-L32 using an older version of the PyPI package index.

I have https://github.com/NixOS/nixpkgs/pull/205878 open to add screed to nixpkgs, extracted from https://github.com/sourmash-bio/sourmash/pull/2393/files#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0R63 where Nix is using only deps from nixpkgs (and so no need to check PyPI updates), but both are not merged yet :upside_down_face:

**Comment by luizirber** [comment]
`nix` is going to fail because the latest there is `screed 1.1.1`, ~will open PR to update~ https://github.com/NixOS/nixpkgs/pull/217269 updates it to `1.1.2`

**Review by luizirber — APPROVED** [review]

**Comment by luizirber** [comment]
`screed` versions are up-to-date enough for nix and conda-forge, so I think we can merge this

**Comment by ctb** [comment]
```
       > ERROR: Could not find a version that satisfies the requirement screed<2,>=1.1.2 (from sourmash) (from versions: none)
       > ERROR: No matching distribution found for screed<2,>=1.1.2
```

**Pull request merged**
