### PR TITLE
[MRG] Add a `MultiIndex` class that wraps multiple Index classes.

### PR DESCRIPTION
**Pull request by ctb**
This PR adds a `MultiIndex` class, which provides a wrapper for other `Index` classes. Each wrapped class should come with a paired location, which can be `None`; if set, the wrapper overrides the filename returned in `search` and `gather` with the paired location.

The PR also adds a `filter` method to `LinearIndex` and `MultiIndex`. This is a harbinger of selectors on scaled/num, https://github.com/dib-lab/sourmash/issues/1072; I'm adding `filter` as an interim solution because I needed the functionality in `sourmash_args` and it made the code much cleaner.

Addresses several of the issues in `DirectoryIndex` issue, #810.

A side effect of switching to `MultiIndex` in various `sourmash_args` functions is that we can remove special-casing of SIGLIST in `_load_databases` and dependent functions. This further simplifies `load_file_as_index` and `load_file_as_signatures`. 👍 

In particular, this approach provides source filename information for where matches are coming from; see [this comment](https://github.com/dib-lab/sourmash/issues/810#issuecomment-652519225) for detailed rationale. Could perhaps replace the SBT `location` attribute in https://github.com/dib-lab/sourmash/pull/1373 with wrapping an SBT in one of these (which seems like a hack in the long term, but could work fine in the short term ;).

This wrapper approach may also provide a partial solution to lazy loading https://github.com/dib-lab/sourmash/issues/1097, because it could support lazy loading of signatures by `Index` classes.

TODO:
- [x] add a few tests that show that source filename in CSV output is correct 🎉 

## Checklist

- [ ] Is it mergeable?
- [ ] `make test` Did it pass the tests?
- [ ] `make coverage` Is the new code covered?
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
Ready for review @luizirber @bluegenes

**Comment by ctb** [comment]
OK, upgraded a bit after some ...excursions. Cleaner, better, more succinct.

**Review by luizirber — APPROVED** [review]

**Comment by luizirber** [comment]
Anything else to add to this, @ctb? Otherwise, go for merging =]

**Comment by ctb** [comment]
thanks @luizirber - I'm doing some important downstream cleanup in https://github.com/dib-lab/sourmash/pull/1406, and will fix any minor nits there.

**Pull request merged**
