### PR TITLE
Feat: on-disk RevIndex based on RocksDB

### PR DESCRIPTION
**Pull request by luizirber**
On-disk RevIndex based on RocksDB, initially implemented in https://github.com/luizirber/2022-06-26-rocksdb-eval
This is the index/core data structure backing https://mastiff.sourmash.bio

There are many changes in the Rust code, so bumping the version to `0.12.0`.

This is mostly not exposed thru the FFI yet. Tests from the from the in-memory `RevIndex` (greyhound) from #1238 were kept working, but it is not well supported (doesn't allow saving/loading from disk, for example), and should be wholly replaced by `sourmash::index::revindex::disk_revindex` (the on-disk RevIndex) in the future.
It is confusing to have these different RevIndex impls in Rust, and I started converging them, but the work is not completely done yet.

#2727 is a better starting point for how `Index` abc/trait should work acrosss Python/Rust, and I started moving the Rust indices to start from a `LinearIndex` and later specialize into a `RevIndex`, which will make easier to translate the work from #2727 for future indices across FFI.

A couple of new concepts introduced in this PR:

- a `Collection` is a `Manifest` + `Storage`. So a zip file like the ones for GTDB databases fit this easily (storage = `ZipStorage`, manifest is read from the zipfile), but a file paths list does too (manifest built from the file paths, storage = `FSStorage`). This goes in a bit of different direction than #1901, which was extending `Storage` to support more functionality. I think `Storage` should stay pretty bare and mostly deal with loading/saving data, but not much knowledge of **what** data is there (this is covered with `Manifest`).

- a `CollectionSet` is a consistent collection of signatures. Consistent here means: same k-size, downsample-compatible for scaled, same moltype. You can create a `CollectionSet` by running `.select()` on a `Collection`. `CollectionSet` is required for building indices (because we shouldn't be building indices mixing k-size/moltype), and greatly simplifies the logic in many places because it is not necessary to check for compatibility.

- `LinearIndex` was rewritten based on `Collection` (and also the `greyhound`/`branchwater` parallelism), and this supports the "parallel search without an index" use case. There is no index construction per se here, pretty much just a thin layer on top of `Collection` implementing functionality expected from indices.

- `Manifest`, `Selection`, and `Picklist` are still incomplete, but the relevant function definitions are in place, need to barrage it with tests (and potentially exposing to Python and reusing the ones there in #2726)

## Feature

- Initial implementation for `Manifest`, `Selection`, and `Picklist` following
  the Python API.
- `Collection` is a new abstraction for working with a set of signatures. A
  collection needs a `Storage` for holding the signatures (on-disk, in-memory,
  or remotely), and a `Manifest` to describe the metadata for each signature.
- Expose CSV parsing and RocksDB errors.
- New module `sourmash::index::revindex::disk_revindex` with the on-disk
  RevIndex implementation based on RocksDB.
- Add `iter` and `iter_mut` methods for `Signature`.
- Add `load_sig` and `save_sig` methods to `Storage` trait for higher-level data
  manipulation and caching.
- Add `spec` method to `Storage` to allow constructing a concrete `Storage` from
  a string description.
- Add `InnerStorage` for synchronizing parallel access to `Storage`
  implementations.
- Add `MemStorage` for keeping signatures in-memory (mostly for debugging and
  testing).

## Refactor

- Rename `HashFunctions` variants to follow camel-case, so `Murmur64Protein`  instead of `murmur64_protein`
- `LinearIndex` is now implemented as a thin layer on top of `Collection`.
- Move `GatherResult` to `sourmash::index` module.
- Move `sourmash::index::revindex` to `sourmash::index::mem_revindex` (this is
  the Greyhound version of revindex, in-memory only). It was also refactored
  internally to build a version of a `LinearIndex` that will be merged in the
  future with `sourmash::index::LinearIndex`
- Move `select` method from `Index` trait into a separate `Select` trait,
  and implement it for `Signature` based on the new `Selection` API.
- Move `SigStore` into `sourmash::storage` module, and remove the generic. Now
  it always stores `Signature`. Also implement `Select` for it.

## Build

- Add new `branchwater` feature (enabled by default), which can be disabled by downstream projects to limit bringing heavy dependencies like rocksdb
- Add new `rkyv` feature (disabled by default), making `MinHash` serializable
  with the `rkyv` crate.
- Add semver checks for CI (so we bump versions accordingly, or avoid breaking changes)
- Reduce features combinations on Rust checks (takes much less time to run) 
- Disable `musllinux`  wheels (need to figure out how to build rocksdb for it)

### CODE REVIEW

**Comment by luizirber** [comment]
Happy anniversary, PR!

You grew a lot in this past year, but alas we need to cut some of the many tentacles you were growing, especially:
- Build system upgrades #2723 #2724 #2725
- The Python/FFI/Rust bridge for Manifest/Picklist/Selection #2726
- The Python/FFI/Rust bridge for RustLinearIndex #2727
- Exposing Mutable/Frozen MinHash in the FFI #2728

I tried this branch against https://github.com/sourmash-bio/mastiff/pull/14, it is still working after removing all the FFI/Python bits (and the Mutable/Frozen MH stuff).

The plan is mostly to:
- merge #2665
- bring up test coverage on the Rust side
- review/merge this as is (maybe merge https://github.com/sourmash-bio/sourmash/tree/ntp/mastiff_roaring_prot into it?)
- release `0.12`
- and work on the follow up PRs later (`0.13` if needed, otherwise `0.12` patch releases)

cc @sourmash-bio/devs, especially @bluegenes as we discussed a few weeks ago!

**Comment by luizirber** [comment]
Some updates: I tried moving closer to how the Python side works with Manifests, and removed quite a lot of the logic for dealing with file paths like the mastiff prototype did.

This mostly means a couple of new concepts:

- a `Collection` is a `Manifest` + `Storage`. So a zip file like the ones for GTDB databases fit this easily (storage = `ZipStorage`, manifest is read from the zipfile), but a file paths list does too (manifest built from the file paths, storage = `FSStorage`). This goes in a bit of different direction than #1901, which was extending `Storage` to support more functionality. I think `Storage` should stay pretty bare and mostly deal with loading/saving data, but not much knowledge of **what** data is there (this is covered with `Manifest`).

- a `CollectionSet` is a consistent collection of signatures. Consistent here means: same k-size, downsample-compatible for scaled, same moltype. You can create a `CollectionSet` by running `.select()` on a `Collection`. `CollectionSet` is required for building indices (because we shouldn't be building indices mixing k-size/moltype), and greatly simplifies the logic in many places because it is not necessary to check for compatibility.

- `LinearIndex` was rewritten based on `Collection` (and also the `greyhound`/`branchwater` parallelism), and this supports the "parallel search without an index" use case. There is no index construction per se here, pretty much just a thin layer on top of `Collection` implementing functionality expected from indices.

- `Manifest`, `Selection`, and `Picklist` are still incomplete, but the relevant function definitions are in place, need to barrage it with tests (and potentially exposing to Python and reusing the ones there in #2726)

I've been building this in parallel with https://github.com/sourmash-bio/mastiff/pull/14 and https://github.com/sourmash-bio/wort/pull/64 to make sure that the indexing/searching continues working in both `branchwater` and `greyhound`, and for testing the expected API for the library. I'm especially interested in being able to continue to operate https://mastiff.sourmash.bio and https://greyhound.sourmash.bio without breaking because of these updates =]
I also want to be able to trigger the next branchwater index creation with manifests, and support updating it using manifests too.

**Comment by ctb** [comment]
> Some updates: I tried moving closer to how the Python side works with Manifests, and removed quite a lot of the logic for dealing with file paths like the mastiff prototype did.
> 
> This mostly means a couple of new concepts:

[ munch ]

This is great! I really like the naming scheme and would be in favor of (eventually) shifting the Python naming over to `Collection` and `CollectionSet`!

Let us know if/when you reach a point where it's helpful for us to poke at these things in our own Rust code. Also happy to help interpret and rewrite/add tests on the Python side... More unit-test style tests are helpful when debugging wonky behavior, as compared to the many functional-style tests we have for a lot of sourmash.

**Comment by luizirber** [comment]
> Let us know if/when you reach a point where it's helpful for us to poke at these things in our own Rust code. Also happy to help interpret and rewrite/add tests on the Python side... More unit-test style tests are helpful when debugging wonky behavior, as compared to the many functional-style tests we have for a lot of sourmash.

Updating a revindex with new sigs is now working (and was very satisfying to implement, it was mostly code removal and dominoes falling in order with `Collection`/`Manifest` ready for use :smile_cat:), I think the last thing before using it more widely is replacing the whole `template`-based selection APIs with `Selection` instead. Will work on it next and ping for review soon.

**Comment by luizirber** [comment]
OK, as this branch is it can load zip collections, and updating them by passing a new manifest with extra rows.
[example](https://github.com/sourmash-bio/mastiff/pull/14/files#diff-d12472074cc9420a357efb51acef9c3b9e0bb5b2a536b18e9485d0d89d7c6282R254-R283) of how that code looks like (also loading from dir+manifest), and also [how it runs in the command line](https://github.com/sourmash-bio/mastiff/pull/14/files#diff-40f53e0c1cff55d538a3b07bd519f9d881b347783d50c14d7d4fac38f8af07b1R7-R44), for
1) indexing from zip collection with explicit manifest (1000 sigs)
2) updating index with same zip collection but an extended manifest (2000 sigs)
3) build an index for a full zip collection (no manifest passed, reuses the full internal one) <- this one covers how I set up greyhound.sourmash.bio, so I can replace greyhound with branchwater as the revindex =]

I'll do some more testing for loading from directory+manifest (what I actually need for SRA branchwater), but the code in this branch shouldn't change much, SO! Time for some light review @sourmash-bio/devs =]

(I'm also establishing a rebase moratorium for now, so this branch should be safe for use as a dependency for PRs in other repos...)

**Comment by ctb** [comment]
@bluegenes can you remind me of the relationship between this branch and the pyo3_dependency on commit ff1092f8f366339caa59d7203f623813228f4356 (which may no longer exist in this repo...?) 

@luizirber my main request is that you update the description of the PR so that we can refer back to this in the future. Specific thoughts for things to add (or maybe questions) -

* this bumps the sourmash-rs package to 0.12, right?
* am I right in understanding that there is no Python API access to the RevIndex? Or does the code in `src/sourmash/index/revindex.py` make use of the updated class?

thanks!

**Comment by luizirber** [comment]
> @bluegenes can you remind me of the relationship between this branch and the pyo3_dependency on commit [ff1092f](https://github.com/sourmash-bio/sourmash/commit/ff1092f8f366339caa59d7203f623813228f4356) (which may no longer exist in this repo...?)

I stopped rebasing this branch and `latest` and started merging instead, so commits should be available (even if the branch is deleted, but maybe keep it around for a bit).

https://github.com/sourmash-bio/pyo3_branchwater/pull/134 uses this PR instead, and can flip to use `0.12.0` once this PR is merged and released. We can open smaller PRs to address shortcomings (and release `0.12.x` versions, or `0.13.0` if we need to change the API), or add features as needed by `pyo3_branchwater`.

> @luizirber my main request is that you update the description of the PR so that we can refer back to this in the future. Specific thoughts for things to add (or maybe questions) -

PR description updated!

> this bumps the sourmash-rs package to 0.12, right?

:+1: 

> am I right in understanding that there is no Python API access to the RevIndex? Or does the code in `src/sourmash/index/revindex.py` make use of the updated class?

Well... there is a light FFI exposing what is now `sourmash::index::revindex::mem_revindex` and is the in-memory RevIndex from #1238. This is not well supported (doesn't allow saving/loading from disk, for example), and should be wholly replaced by `sourmash::index::revindex::disk_revindex` (the on-disk RevIndex).

It is confusing to have these different RevIndex impls in Rust, and I started converging them, but the work is not completely done yet.

Nonetheless, I kept the current tests for the Python RevIndex working, but there are not many of them. #2727 is a better starting point for how `Index` abc/trait should work acrosss Python/Rust, and I started moving the Rust indices to start from a `LinearIndex` and later specialize into a `RevIndex`, which will make easier to translate the work from #2727 for future indices across FFI.

**Comment by ctb** [comment]
thanks!

@bluegenes I leave this in your capable hands ;)

**Review by ctb — APPROVED** [review]

**Comment by ctb** [comment]
Per out of band conversation: merge now, release sourmash-rs 0.12.0, integrate/test/fix in https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/134

**Pull request merged**
