### PR TITLE
[MRG] Fix some `sourmash sig cat` tests that rely on pathlists.

### PR DESCRIPTION
**Pull request by ctb**
PR into https://github.com/dib-lab/sourmash/pull/1469. Fixes remaining tests, by making the order of the signatures deterministic before doing the repr. Also adds explicit test for number-of-signatures.

@keyabarve

### CODE REVIEW

**Comment by keyabarve** [comment]
@ctb I looked at the code and I understood most of the code you added except for the line: `siglist.sort(key = lambda x: x.md5sum())` I understand that this sorts the signatures, but what I'm having difficulty with is where the rest of the variables such as "key" and "x" come from. I also wanted to know what "lambda" and "md5sum" are exactly doing.

**Comment by keyabarve** [comment]
Could you also tell me how I can get these changes you made on my computer? Should I just do `git pull` or should I pull from a specific branch and then `git push`?

**Comment by ctb** [comment]
> Could you also tell me how I can get these changes you made on my computer? Should I just do `git pull` or should I pull from a specific branch and then `git push`?

you should be able to merge from the github interface, and then pull into your branch by doing `git pull`.

alternatively you can also do `git pull origin KB_1430_ctb2` and then `git push`.

**Comment by ctb** [comment]
> @ctb I looked at the code and I understood most of the code you added except for the line: `siglist.sort(key = lambda x: x.md5sum())` I understand that this sorts the signatures, but what I'm having difficulty with is where the rest of the variables such as "key" and "x" come from. I also wanted to know what "lambda" and "md5sum" are exactly doing.

`sort` is a generic method on Python lists. `lambda` makes anonymous functions. `md5sum()` is method on `SourmashSignature` objects that returns a content-based md5sum hash. So, what's going on here is we're sorting the siglist contents by a unique identifier.

**Pull request merged**
