### PR TITLE
[WIP] properly track duplicate signatures in `sourmash lca index`

### PR DESCRIPTION
**Pull request by ctb**
PR into https://github.com/dib-lab/sourmash/pull/1542, which was closed in favor of #1543. Should probably be merged into #1543 instead, but I'm going to keep it here until @bluegenes can take a look.

This PR fixes some signature tracking that more clearly surfaces the problem described in  
https://github.com/dib-lab/sourmash/issues/1573 - `sourmash lca index` eliminates identical signatures before recording their identifiers.

### CODE REVIEW

**Comment by bluegenes** [comment]
This reporting fix lgtm! Shall we merge into #1543?

I'd really like if we came up with some strategies for handling duplicated md5sum's downstream (e.g. report them as alternative match results?), but that seems like a separate consideration :)

**Comment by ctb** [comment]
> This reporting fix lgtm! Shall we merge into #1543?

sure!
 
> I'd really like if we came up with some strategies for handling duplicated md5sum's downstream (e.g. report them as alternative match results?), but that seems like a separate consideration :)

I can see that it would be important for taxonomy... I guess let's create an issue!

**Comment by bluegenes** [comment]
@ctb could I ask you to look at these conflicts? thx!

**Comment by ctb** [comment]
done!

**Comment by ctb** [comment]
(and merged)

**Pull request merged**
