### PR TITLE
MRG: add label output & input options to `compare` and `plot`, for better customization

### LINKED ISSUE #2452: upgrade labels on `sourmash plot` with `--labels-from` or some such
Labels on `sourmash plot` are complicated and ugly ;(.

Random thought: we could add a `--labels-to` option to `sourmash compare` that supports a simple labeling output spreadsheet, and then support a `--labels-from` option with `sourmash plot`.

### LINKED ISSUE #2915: allow users to adjust labels, etc. in plot_dendrogram function
per [@LilyAnderssonLee! review](https://github.com/pyOpenSci/software-submission/issues/129#issuecomment-1838233643)

> Is it possible to include arguments to allow users to adjust the legends of both matrix and dendrogram plots in the function mentioned in the example: `sourmash plot --pdf --lables ecoli_cmp` ?

### PR DESCRIPTION
**Pull request by ctb**
Adds `sourmash compare --labels-to` and `sourmash plot --labels-from` to support better label customization.

Fixes https://github.com/sourmash-bio/sourmash/issues/2452
Fixes https://github.com/sourmash-bio/sourmash/issues/2915

## `sourmash compare --labels-to`

This command will generate a 'labels-to' file. Running:
```
sourmash compare tests/test-data/demo/*.sig -o compare-demo \
    --labels-to compare-demo-labels.csv
```
will produce a file that looks like this:

file `compare-demo-labels.csv`:
```csv
order,md5,label,name,filename,signature_file
1,60f7e23c24a8d94791cc7a8680c493f9,SRR2060939_1.fastq.gz,,SRR2060939_1.fastq.gz,../tests/test-data/demo/SRR2060939_1.sig
2,4e94e60265e04f0763142e20b52c0da1,SRR2060939_2.fastq.gz,,SRR2060939_2.fastq.gz,../tests/test-data/demo/SRR2060939_2.sig
3,f71e78178af9e45e6f1d87a0c53c465c,SRR2241509_1.fastq.gz,,SRR2241509_1.fastq.gz,../tests/test-data/demo/SRR2241509_1.sig
4,6d6e87e1154e95b279e5e7db414bc37b,SRR2255622_1.fastq.gz,,SRR2255622_1.fastq.gz,../tests/test-data/demo/SRR2255622_1.sig
5,0107d767a345eff67ecdaed2ee5cd7ba,SRR453566_1.fastq.gz,,SRR453566_1.fastq.gz,../tests/test-data/demo/SRR453566_1.sig
6,f0c834bc306651d2b9321fb21d3e8d8f,SRR453569_1.fastq.gz,,SRR453569_1.fastq.gz,../tests/test-data/demo/SRR453569_1.sig
7,b59473c94ff2889eca5d7165936e64b3,SRR453570_1.fastq.gz,,SRR453570_1.fastq.gz,../tests/test-data/demo/SRR453570_1.sig
```

The `label` column in this file can be edited to suit the user's needs; the index column is `order`, and all other columns can be ignored or deleted or updated without consequence.

## `sourmash plot --labels-from`

This command will load labels from a file. Running:
```
sourmash plot --labels-from compare-demo-new-labels.csv compare-demo
```
uses the `label` column from the CSV as labels, in the order specified by the `order` column (interpreted as integers and sorted from lowest to highest). All other columns are ignored.

## Example in a Jupyter Notebook

Some example code for updating the labels is available here:

https://github.com/sourmash-bio/sourmash/blob/compare_labels/doc/plotting-compare.ipynb

## TODO

- [x] add test for `args.labeltext and args.labels_from` check
- [x] check the notebook update

## Future:

- [ ] Consider switching to `LinearIndex` in the signature loading code, as that would let us maintain the location in the code without the current machinations. Also worth thinking about enabling lazy loading, which some future `Index`-code based modification might support.
- [ ] consider if and how to validate --labels-from CSV file...

### CODE REVIEW

**Comment by peterjc** [comment]
Other possible names for the "order" column: "sort" or "index" - I have no strong preference, but can see how I might use this were my labels didn't have an alphabetic sorting.

**Comment by ctb** [comment]
7ffcb7bf changes `order` to `sort_order`

**Comment by ctb** [comment]
Ready for review & merge @sourmash-bio/devs !

**Review by bluegenes — APPROVED** [review]
lgtm!

**Comment by ctb** [comment]
🎉

**Pull request merged**
