### PR TITLE
[MRG] Fixing tests that fail to close files that they open

### LINKED ISSUE #1435: fix tests that fail to close files that they open
There are several tests in `test_lca.py` that are causing warnings during the tests, because I did a bad thing and opened files without closing them.

The three tests are:
```
test_single_summarize_to_output
test_single_classify_to_output
test_single_classify_to_output_no_name
```
and they all use some variant of this code,
```
outdata = open(os.path.join(location, 'outfile.txt'), 'rt').read()
```
which doesn't close the file. This results in a warning when py.test runs the tests.

The proper usage is something like
```
with open(...) as fp:
   outdata = fp.read()
```
which will use a context manager to close the file after the `with` block.

Fix!

### PR DESCRIPTION
**Pull request by keyabarve**
Fixes #1435

### CODE REVIEW

**Comment by keyabarve** [comment]
Please review. @ctb

**Review by ctb — APPROVED** [review]
Nice work! shall I merge? (put [MRG] in front of PR title if you want me to merge, or [WIP] in front of title if it remains a work-in-progress)

**Comment by keyabarve** [comment]
Thanks! Sure!

**Comment by ctb** [comment]
thanks! 🎉

**Pull request merged**
