### PR TITLE
[MRG] less stringent size accuracy parameters

### PR DESCRIPTION
**Pull request by bluegenes**
As a result of our size accuracy estimation, we're zero'ing out a lot of ANI values that, upon comparison, seem quite good. I'm not convinced the parameters I've put in here will be final, but I _am_ convinced that the parameters we have in `latest` right now are far too stringent. 

For the params we have in the current release, < 20% of comparisons (using GTDB genomes) are passing threshold to allow ANI estimation (https://github.com/bluegenes/2022-protein-kmers-workflow/blob/main/notebooks/11.size-accuracy-estimation.ipynb, see [6])

For comparison with mapping-based ANI values, see: 
https://github.com/bluegenes/2022-protein-kmers-workflow/blob/main/notebooks/size-acc-vs-ANI.ipynb.
Values we're zero'ing out seem quite similar to values we're keeping, in terms of comparisons to mapping-based values.

### CODE REVIEW

**Comment by bluegenes** [comment]
@ctb ready for review.

**Comment by ctb** [comment]
@bluegenes I'm finding it hard to review this 'un ;). Could you choose one figure to include in this PR, along with a brief description of how you adjusted the parameters? thanks!

**Comment by ctb** [comment]
(you can just include in the figure in the comments here - I just don't see a single clear-cut figure in that notebook that I can screengrab)

**Comment by bluegenes** [comment]
> @bluegenes I'm finding it hard to review this 'un ;). Could you choose one figure to include in this PR, along with a brief description of how you adjusted the parameters? thanks!
(you can just include in the figure in the comments here - I just don't see a single clear-cut figure in that notebook that I can screengrab)

This is kind of my point -- I don't have a good reason for selecting the _specific_ parameters that I've now selected, but the parameters we currently have are impractical, given that only ~20% of GTDB genomes pass the threshold, which means that in practice, most results will not have ANI values reported. This is not desirable functionality.

For each sketch, we're using the equation [here](https://github.com/sourmash-bio/sourmash/issues/1798#issuecomment-1015762466) to be at least `95%` sure that the FracMinHash cardinality is off by less than `5% relative error` (the two tunable parameters). In this PR, I've kept the probability at 95% and extended the relative error to 20%, which results in nearly all of the GTDB genomes passing size estimation threshold.

My main issue is that I'm not convinced that sketches that do not pass threshold are giving us bad ANI values, but perhaps I'm not evaluating the right things?

Here is a slightly different version of the plot I linked above. Using our current thresholds, points are colored by passing (green) / failing (warm colors) size accuracy threshold. Here, I've plotted ANIb values (using `pyani`) vs `ANIdiff`, which is `sourmash ANI - ANIb`. While it does appear that the passing points are in the middle of the distribution, there are no clear distinctions that suggest the "failing" points are poor ANI results. 

image

Do you have any insight on how to proceed, @dkoslicki?

**Comment by ctb** [comment]
I think that's the explanation I wanted attached to this PR - thank you :)

**Review by ctb — APPROVED** [review]

**Comment by dkoslicki** [comment]
@bluegenes I agree that the settings are too stringent. Doing some playing around, as soon as the number of distinct k-mers gets large enough (say 50 or so), then the cardinality estimate seems to be "good enough". I.e. the bias is only present when there are few k-mers, and this is the only regime where the cardinality estimate would be off too. Given, I assume, that all the sequences that you're testing have at least 50 k-mers, then you may consider changing the threshold to give you something more like 99% passing than ~80% passing. Eg. by decreasing `confidence` or further increasing `relative_error`

**Pull request merged**
