### PR TITLE
[MRG] return Err for angular_similarity when abundance tracking is off

### LINKED ISSUE #898: fix unnamed exception in rust angular_similarity method.
`angular_similarity` on MinHash objects fails with an unnamed exception when abundances are not available. #fixme.

### PR DESCRIPTION
**Pull request by ctb**
Replaces `unimplemented!()` in `KmerMinHash` and `KmerMinHashBTree` `angular_similarity` functions with appropriate error handling.

Fixes https://github.com/sourmash-bio/sourmash/issues/898.

### CODE REVIEW

**Comment by ctb** [comment]
Ready for review @luizirber @mr-eyes

**Review by mr-eyes — APPROVED** [review]
Looks very good to me.

**Comment by ctb** [comment]
cool, thanks! will wait for @luizirber to have a chance to comment too, since it's early days for me & 🦀

**Review by luizirber — APPROVED** [review]
Nice!

**Comment by ctb** [comment]
@luizirber looks like I need to re-run cbindgen, yes? The installation instructions say I should add it to my `Cargo.toml` but it's not in sourmash's `Cargo.toml`...?

**Comment by ctb** [comment]
(I see the Makefile rule for `include/sourmash.h`, just curious about how I should install cbindgen if it's a non-standard way?)

**Comment by ctb** [comment]
oh. The [actual docs](https://github.com/eqrion/cbindgen/blob/HEAD/docs.md) just say to use `cargo install cbindgen`, and that worked just fine!

Updated `include/sourmash.h` in 9b1885a9. Will merge once tests pass.

**Pull request merged**
