### PR TITLE
[WIP] Remove min_n_below from search code

### PR DESCRIPTION
**Pull request by luizirber**
There are three main cases when searching an index in sourmash (I'll use `Q` as query signature and `s` as a signature/internal node for the analysis):

## Case 1: similarity searches

We want to find any signature that is above a similarity threshold in a collection:
`J(Q, s) = |Q ∩ s| / |Q ∪ s|`. Since `|Q| <= |Q ∪ s|`, we can use `|Q|` as an upper bound (because it can overestimate the similarity, but never underestimate).

## Case 2: containment searches

We want to find what signatures are above a containment threshold to the query (with `sourmash search --containment`) or which one is the best match (maximizes the query containment in the signature), as in `sourmash gather`.
`C(Q, s) = |Q ∩ s| / |Q|`. Similar to case 1, we just need `|Q|`.

## Case 3: reverse containment searches

We want to find what signatures are above a containment threshold to the query like case 2, but we want to maximize the signature containment (not the query containment).
`C(s, Q) = |Q ∩ s| / |s|`.
This is the case where `min_n_below` is necessary to bound `|s|`. It is also not used in any place in sourmash.

# `min_n_below` is too pessimistic, and ends up making search slower.

Because the only place we really need `min_n_below` is not a use case for sourmash, the consequence is that `min_n_below` is too pessimistic when pruning subtrees during search, and it ends up making search slower.

This all came from the realization that I was thinking about `gather` backwards. The best match in `gather` maximizes `C(Q,s)` and not `C(s,Q)`. An example: let's say there is a small viral scaled MinHash `s` with only one hash. If `gather` was implemented with `C(s, Q)` and the hash is in `Q`, then `s` would be the best match (because `C(s, Q) = 1`). But maximizing `C(Q, s)` is really finding the largest intersection between the query and a signature in an index, and so if there is a larger scaled MinHash `s'` with smaller `C(s', Q)` but larger `C(Q, s')`, then it is going to be selected (and its hashes will be removed from the query for the next round).

## TODO

- [ ] More tests, I'm not so sure current tests are checking for corner cases...

## Checklist

- [ ] Is it mergeable?
- [ ] `make test` Did it pass the tests?
- [ ] `make coverage` Is the new code covered?
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
ok, this is pretty neat :). On first glance, I agree with your calculations!

**Comment by ctb** [comment]
(I also agree about More Testing Needed for edge cases...)

**Comment by luizirber** [comment]
Need more checks, and the machine I ran the benchmarks was running other processes too, but... wow.

image

**Comment by luizirber** [comment]
I updated the [notebook](https://github.com/luizirber/2021-04-17-angular-bound/blob/eb93f093652df6f7494e304fe46ff091d761b1bb/analysis.ipynb) in [luizirber/2021-04-17-angular-bound](https://github.com/luizirber/2021-04-17-angular-bound), where I'm doing some analysis on the proposed upper bound for angular similarity. I ended up going with the second approach because it overestimates way less than the first one.

I used `hypothesis` to generate 5000 examples and then selected cases where the angular similarity was larger than `0.1` and the difference between angular similarity and the upper bound was larger than `0.1`. When I plot an histogram for the first approach ([`a_sq += 1`](https://github.com/dib-lab/sourmash/pull/1137/files#diff-1280382f54ecf5d2d52da0aad6e4aec03abd3409a186f800af2596224987015fR178)), this is the result:
image

and for the second approach ([`a_sq += abund * abund`](https://github.com/dib-lab/sourmash/pull/1137/files#diff-1280382f54ecf5d2d52da0aad6e4aec03abd3409a186f800af2596224987015fR177)):
image

**Comment by ctb** [comment]
@luizirber is this worth pursuing (or at least keeping the PR up to date :), or has this been superseded by other changes?

**Comment by luizirber** [comment]
> @luizirber is this worth pursuing (or at least keeping the PR up to date :), or has this been superseded by other changes?

Maybe? But I'm closing this PR because I won't work on it.

**Pull request closed without merging**
