### PR TITLE
[MRG] Fix max hash deprecation warnings

### LINKED ISSUE #1296: resolve sourmash deprecation warnings for 4.0 release
the tests currently spit out a LOT of warnings. fixme.

### LINKED ISSUE #1297: update required screed version to 1.0.5
https://github.com/dib-lab/screed/releases/tag/v1.0.5 drops support for Python before 3.7, and removes deprecation warnings.

### PR DESCRIPTION
**Pull request by ctb**
In https://github.com/dib-lab/sourmash/pull/1128/, we deprecated direct use of `max_hash` attribute as of 3.5, slated for removal in 5.0. This PR cleans up the sourmash codebase so that the associated deprecation warnings do not come from internal code, at least 😄 

Specifically, this PR -
* removes `MinHash.max_hash` from most code in sourmash, including tests.
* creates a new private `_max_hash` proprety on class `MinHash`.
* uses `Minhash._max_hash` in the few remaining places in the code base.

I also updated the screed version requirement in `setup.cfg` to v1.0.5, which removes another DeprecationWarning from old py2.7/3.6 code.

Fixes #1296, clean up deprecation warnings
Fixes https://github.com/dib-lab/sourmash/issues/1297, update screed version

## Checklist

- [ ] Is it mergeable?
- [ ] `make test` Did it pass the tests?
- [ ] `make coverage` Is the new code covered?
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
ready for review @luizirber

**Comment by luizirber** [comment]
Next PR down the line from this one is removing `max_hash` from `MinHash.__init__`, and I think that will remove most of the uses of `MinHash._max_hash` too?

**Review by luizirber — APPROVED** [review]

**Comment by ctb** [comment]
> Next PR down the line from this one is removing `max_hash` from `MinHash.__init__`, and I think that will remove most of the uses of `MinHash._max_hash` too?

Do you mean, that SHOULD be the next PR down the line? I'm not sure I want to do that for 4.0; involves a few more changes, and might break pickled MinHash objects.

**Comment by luizirber** [comment]
> Do you mean, that SHOULD be the next PR down the line? I'm not sure I want to do that for 4.0; involves a few more changes, and might break pickled MinHash objects.

I sure hope no one is depending on storing pickled MinHash objects :grimacing:

**Comment by ctb** [comment]
On Thu, Feb 04, 2021 at 04:23:52PM -0800, Luiz Irber wrote:
> > Do you mean, that SHOULD be the next PR down the line? I'm not sure I want to do that for 4.0; involves a few more changes, and might break pickled MinHash objects.
> 
> I sure hope no one is depending on storing pickled MinHash objects :grimacing: 
I think I might be, in spacegraphcats :grin:

**Comment by luizirber** [comment]
>> I sure hope no one is depending on storing pickled MinHash objects

> I think I might be, in spacegraphcats

May be worth a look (faster and safer pickle): https://jcristharif.com/quickle/

**Pull request merged**
