### PR TITLE
done 2/3 changes

### PR DESCRIPTION
**Pull request by himanshu007-creator**
Please replace this text with:

* a brief description of your changes in this PR
* which issues this fixes in the issue tracker, if any #1451 
* which issues this PR is related to, if any #1451

Please also be sure to note here if file formats, command-line
interface, and/or the top-level sourmash API will change because of
this PR.

If you are a new contributor, please provide
[your ORCID](https://orcid.org).  If you don't have one, please
[register for one](https://orcid.org/register).

Once the items above are done, and all checks pass, request a review!

### CODE REVIEW

**Comment by himanshu007-creator** [comment]
modify the new test to create a text file containing the path to input_sig

please elaborate how to execute this step . Thanks🙂

**Comment by ctb** [comment]
>> modify the new test to create a text file containing the path to input_sig
> 
> please elaborate how to execute this step . Thanks🙂

hi! sure - take a look at [`test_multi_index_load_from_pathlist_3_zipfile`](https://github.com/dib-lab/sourmash/blob/latest/tests/test_index.py#L900) for an example. Instead of `c.output('filelist.txt')` use `os.path.join(location, 'filelist.txt')`.

**Comment by himanshu007-creator** [comment]
> > > modify the new test to create a text file containing the path to input_sig
> > 
> > 
> > please elaborate how to execute this step . Thanks🙂
> 
> hi! sure - take a look at [`test_multi_index_load_from_pathlist_3_zipfile`](https://github.com/dib-lab/sourmash/blob/latest/tests/test_index.py#L900) for an example. Instead of `c.output('filelist.txt')` use `os.path.join(location, 'filelist.txt')`.

can you tell exact line in the code that needs to be changes in code?

**Comment by ctb** [comment]
insert new code before line 1451, and then change line 1451 appropriately.

```
     input_sig = utils.get_test_data('lca/TARA_ASE_MAG_00031.sig')

        cmd = ['lca', 'summarize', '--db', db1, '--query-from-file', input_sig]
```

1. create a text file containing the path from the `input_sig` variable;
2. change the `input_sig` on line 1451 to be the name of the text file.

**Pull request closed without merging**
