### PR TITLE
[MRG] update authors in setup.cfg

### LINKED ISSUE #444: update authors in setup.py etc.
right now it's just me!

### LINKED ISSUE #622: Update author list for 4.0
`git shortlog --summary --numbered` reports:

```
   746  C. Titus Brown
    94  Luiz Irber
    34  Laurent Gautier
    17  Tim Head
     7  Connor Tiffany
     5  Olga Botvinnik
     4  Taylor Reiter
     3  brooksph
     3  S. Joshua Swamidass
     2  Titus Brown
     2  Harriet Alexander
     1  swamidass
     1  Arfon Smith
     1  Connor T. Skennerton
     1  Daniel Standage
     1  Katrin Leinweber
     1  Phillip Brooks
     1  Tessa Pierce
     1  ljcohen
     1  pyup.io bot
     1  Andreas Sjödin
```

I suspect @luizirber numbers are low because of squash and merge :)

I will assume that @halexand @betatim @olgabot @taylorreiter @brooksph @standage @bluegenes and @ljcohen have no problem being co-authors. (Please let me know here or privately if you don't want to be listed on the JOSS paper!)

Arfon I will exclude because his commit e15e197981f5 was only to update the publication record  :).

pyup.io is a bot... :)

That leaves:

* Laurent Gautier - many contributions!
* Connor Tiffany - revamped documentation (RST -> Markdown), #356 
* S. Joshua Swamidass - updated some tests and code #138
* Connor Skennerton - commit 41ad6b9a added code checking on file existence
* Katrin Leinweber - commit d2e2e3fd5, updating documentation.
* Andreas Sjodin - commit a5c60c7, updating documentation.

### PR DESCRIPTION
**Pull request by ctb**
this PR puts all of the authors in #622 into setup.cfg / PyPI authors list, and sets maintainers to be me and @luizirber, per https://github.com/dib-lab/sourmash/issues/444#issuecomment-788141604.

Fixes https://github.com/dib-lab/sourmash/issues/444
Fixes https://github.com/dib-lab/sourmash/issues/622

## Checklist

- [ ] Is it mergeable?
- [ ] `make test` Did it pass the tests?
- [ ] `make coverage` Is the new code covered?
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
ready for review @luizirber

**Review by luizirber — APPROVED** [review]

**Comment by ctb** [comment]
thanks!

**Comment by taylorreiter** [comment]
Can I be added too?

**Comment by ctb** [comment]
On Tue, Mar 02, 2021 at 10:08:15AM -0800, Taylor Reiter wrote:
> Can I be added too?

<sigh> sorry, Taylor. Thought I'd gotten you!

**Pull request merged**
