### PR TITLE
MRG: fix `calculate_gather_stats` `threshold=0` bug

### LINKED ISSUE #3051: bug in `calculate_gather_stats` (rocksdb gather)
(The only way to run this is currently through `sourmash_branchwater_plugin`)

There's a `panic` coming from `calculate_gather_stats`:
```
Reading query(s) from: 'output.spillover/spillover.dna.zip'
WARNING: skipped 234962 query paths - no compatible signatures.
Loaded 33566 query signature(s)
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/sourmash_plugin_branchwater_1709096111241/_build_env/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sourmash-0.13.0/src/index/mod.rs:297:55:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /home/conda/feedstock_root/build_artifacts/sourmash_plugin_branchwater_1709096111241/_build_env/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sourmash-0.13.0/src/index/mod.rs:297:55:
called `Option::unwrap()` on a `None` value
```

The relevant line is 
```
median_abund = median(abunds.iter().cloned()).unwrap();
```
so `unwrap()` is panicking if the median is None. 

`median` returns `Option<f64>`, so I should either: 
1. handle the Option properly rather than calling `unwrap`, or
2. make sure we don't call median on an empty `abunds` vector. Tbh this should never happen, so probably best to track that down rather than just handling `None`.

### Checking the `median` function:
https://docs.rs/streaming-stats/0.2.3/stats/fn.median.html
`None` is only returned when inflated_abundances is an empty vector.
`median` from `streaming-stats`: https://github.com/BurntSushi/rust-stats/blob/aaa17b69c141788ceb62b8f9a40ebbb63cedce07/src/sorted.rs#L95
```
pub fn median_on_sorted<T>(data: &[T]) -> Option<f64>
        where T: PartialOrd + ToPrimitive {
    Some(match data.len() {
        0 => return None,
        1 => data[0].to_f64().unwrap(),
        len if len % 2 == 0 => {
            let v1 = data[(len / 2) - 1].to_f64().unwrap();
            let v2 = data[len / 2].to_f64().unwrap();
            (v1 + v2) / 2.0
        }
        len => {
            data[len / 2].to_f64().unwrap()
        }
    })
}
```
### Checking `abunds` vector create via `inflated_abundances`:

 The abundance weighting should only be happening when:
 1. there are matches between query and match sig
 4. the query was built with `--track-abundance`.

How are we getting an empty abunds vector?

**UPDATE:** This turns out to happen because we try to calculate gather stats when `match_size` = 0!

### PR DESCRIPTION
**Pull request by bluegenes**
The error shows up when we try to calculate abundance info with a `match_size` of 0:
```
match: GCF_002819265.1 Choclo virus, match_size: 0, query_size: 273, query_trackabund: true
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/ntpierce/sourmash/src/core/src/index/mod.rs:301:55
```

...we should never be trying to calculate statistics on `match_size` of 0, but the logic is currently `match_size >= threshold`.This includes a check to break if `match_size` is 0.

- fixes #3051

### CODE REVIEW

**Comment by bluegenes** [comment]
@sourmash-bio/devs ready for review!

**Review by ctb — APPROVED** [review]

**Comment by ctb** [comment]
Do we need a test? I'm ok if the answer is "no".

**Comment by bluegenes** [comment]
> Do we need a test? I'm ok if the answer is "no".

We don't currently have tests for any of `disk_revindex.rs` (though I do have python tests for running + results in `sourmash_plugin_branchwater`), so adding one here would require a fair bit of setup. Can we put this to an issue to handle later? I can add a `--threshold 0` test to `sourmash_plugin_branchwater`.

**Comment by ctb** [comment]
> > Do we need a test? I'm ok if the answer is "no".
> 
> We don't currently have tests for any of `disk_revindex.rs` (though I do have python tests for running + results in `sourmash_plugin_branchwater`), so adding one here would require a fair bit of setup. Can we put this to an issue to handle later? I can add a `--threshold 0` test to `sourmash_plugin_branchwater`.

sure!

**Comment by luizirber** [comment]
> We don't currently have tests for any of `disk_revindex.rs` (though I do have python tests for running + results in `sourmash_plugin_branchwater`), so adding one here would require a fair bit of setup. 

Tests for disk_revindex are at the [revindex module](https://github.com/sourmash-bio/sourmash/blob/fe4790f4828e39104141c895768261ed7cf411a1/src/core/src/index/revindex/mod.rs#L446), because `sourmash::index::revindex::RevIndex` acts as an unified interface for disk and mem revindex. Tho only the disk one is really used =]

**Pull request merged**
