### PR TITLE
[MRG] support loading of empty picklists

### LINKED ISSUE #2096: consider supporting empty picklists in the picklist API
in https://github.com/sourmash-bio/sourmash/pull/1924/ (released in v4.4.0), we changed picklist loading so that it failed on empty picklist files, among other things. this required some slightly ugly code to be needed in charcoal in https://github.com/dib-lab/charcoal/pull/215, ref in https://github.com/sourmash-bio/sourmash/issues/2094.

It would be simple to add an `allow_empty` flag on picklist loading. Maybe we should do that.

### PR DESCRIPTION
**Pull request by ctb**
Support `allow_empty=True` on `SignaturePicklist.load(...)`.

Also adds a `test_picklist.py` file and `tests/test-data/picklist/` directory, for future picklist tests.

Fixes https://github.com/sourmash-bio/sourmash/issues/2096

### CODE REVIEW

**Comment by ctb** [comment]
Ready for review & merge @sourmash-bio/devs

**Comment by ctb** [comment]
Note: the rust checks that are failing have nothing to do with this PR. 🤷

**Comment by ccbaumler** [comment]
I notice one other warning about mamba in the `dev_env.yml`:

> mamba
> Mamba support is still experimental and can result in differently solved environments!

Is this at all a concern? 
Would it be best to specify the version of Mamba to use in the `yml` instead of the latest?

**Comment by ctb** [comment]
> I notice one other warning about mamba in the `dev_env.yml`:
> 
> > mamba
> > Mamba support is still experimental and can result in differently solved environments!
> 
> Is this at all a concern? Would it be best to specify the version of Mamba to use in the `yml` instead of the latest?

I actually don't find any references anywhere to a `dev_env.yml` - where are you seeing this? :)

In any case, if it's not related to either the functionality being implemented for the PR, or the changed files, then it's not relevant to the PR & you should start a new issue with that as a question, I think!

**Comment by ccbaumler** [comment]
I created an issue like you suggested to investigate this warning further. See issue `Mamba support is experimental 2109`

The warning is located in any workflow that is under the Actions>Dev Env Instructions.

**Comment by ctb** [comment]
> I created an issue like you suggested to investigate this warning further. See issue `Mamba support is experimental 2109`
> 
> The warning is located in any workflow that is under the Actions>Dev Env Instructions.

thx - yes, it was in `dev_envs.yml` under `.github/workflows/`, which was easier to find than `dev_env.yml` which does not exist :)

note you can refer to other issues in a few different ways:
* paste in the link https://github.com/sourmash-bio/sourmash/issues
* use a markdown link, like so: [mamba support is experimental](https://github.com/sourmash-bio/sourmash/issues)
* referring to issue number in a non-verbatim link with a pound sign, e.g. #2109

all of these will reverse link that issue to here, which is nice!

**Review by ccbaumler — APPROVED** [review]
LGTM

**Comment by ctb** [comment]
thanks!

**Pull request merged**
