### PR TITLE
[MRG] Upgrading command-line docs for `sourmash sig` subcommands

### LINKED ISSUE #1612: upgrade command-line docs for `sourmash sig` subcommands
The various `sourmash sig` subcommands (cat, extract, etc) do not give very useful information when invoked on the command line without any arguments --

```
% sourmash sig cat
usage:  cat [-h] [-q] [-o FILE] [-u] signatures [signatures ...]
 cat: error: the following arguments are required: signatures
```

to address this:
* pick a sourmash sig subcommand that doesn't have useful output when run w/o arguments
* find the relevant subcommand file (e.g. `src/sourmash/cli/sig/cat.py`)
* in that file, add a `description=__doc__` and `usage=usage` argument to the `subparser.add_parser(...)` call; see `src/sourmash/compute.py` for an example
* initialize the `__doc__` and `usage` strings from the command-line docs
* ask for initial review and someone will work with you on the text

This can also be done for many other commands than just the `sourmash sig`, too ;).

### LINKED ISSUE #2070: fix `sourmash sig split` usage string
running `sourmash sig` shows:
```
Manipulate signature files:
  Operations
...
          sourmash sig split --help         concatenate signature files
...
```
which is incorrect - should be `split multiple signatures into individual files`

### PR DESCRIPTION
**Pull request by keyabarve**
Fixes #1612
Fixes https://github.com/sourmash-bio/sourmash/issues/2070

- Pick a `sourmash sig` subcommand that doesn't have useful output when run w/o arguments.
- Find the relevant subcommand file.
- In that file, add a `description=__doc__` and `usage=usage` argument to the `subparser.add_parser(...)` call.
- Initialize the `__doc__` and `usage` strings from the command-line docs.
- This can also be done for many other commands than just the `sourmash sig`.

### CODE REVIEW

**Comment by ctb** [comment]
(I think you should avoid using "Fixes ..." unless it resolves the entire
issue; in this case, just use "See #1612" or something similar. Fixes
will autoclose the issue when it's merged, which we don't want.)

**Comment by keyabarve** [comment]
@ctb In `src/sourmash/cli/sig/cat.py`, when I do this: `subparser = subparsers.add_parser('cat', description=__doc__, usage=usage)` it says that `usage` is not defined. Where and how can I define it?
Also, how can I do this: "Initialize the `__doc__` and `usage` strings from the command-line docs."

**Comment by ctb** [comment]
> @ctb In `src/sourmash/cli/sig/cat.py`, when I do this: `subparser = subparsers.add_parser('cat', description=__doc__, usage=usage)` it says that `usage` is not defined. Where and how can I define it?

Please see the documentation for argparse for what `usage` should be, and also see examples within the current codebase.

> Also, how can I do this: "Initialize the `__doc__` and `usage` strings from the command-line docs."

The command-line docs are part of the sourmash documentation and can be found under `doc/`.

**Comment by keyabarve** [comment]
> > @ctb In `src/sourmash/cli/sig/cat.py`, when I do this: `subparser = subparsers.add_parser('cat', description=__doc__, usage=usage)` it says that `usage` is not defined. Where and how can I define it?
> 
> Please see the documentation for argparse for what `usage` should be, and also see examples within the current codebase.
> 
Alright!

> > Also, how can I do this: "Initialize the `__doc__` and `usage` strings from the command-line docs."
> 
> The command-line docs are part of the sourmash documentation and can be found under `doc/`.
>
I'm not sure what it means to initialize the strings from the docs.

**Comment by ctb** [comment]
> > The command-line docs are part of the sourmash documentation and can be found under `doc/`.
> 
> I'm not sure what it means to initialize the strings from the docs.

There is existing documentation in the doc files. Copy it from there into the codebase.

**Comment by keyabarve** [comment]
Okay, thanks!

**Comment by keyabarve** [comment]
@ctb I have added the details for the `cat` command. Could you please take a look at it and tell me whether I need to make any changes or if I could proceed with other commands?

**Comment by ctb** [comment]
looks good - does it print out helpful stuff when you do `sourmash sig cat -h`?

**Comment by keyabarve** [comment]
> looks good - does it print out helpful stuff when you do `sourmash sig cat -h`?
>
Thank you. Yes, I think it does. This is the output:
```

== This is sourmash version 4.1.2.dev6+g87a908c.d20210609. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

usage: 

### `sourmash signature cat` - concatenate multiple signatures together

Concatenate signature files.

For example,

sourmash signature cat file1.sig file2.sig -o all.sig

will combine all signatures in `file1.sig` and `file2.sig` and put them
in the file `all.sig`.

concatenate signature files

positional arguments:
  signatures

optional arguments:
  -h, --help            show this help message and exit
  --from-file FROM_FILE
                        a text file containing a list of files to load signatures from
  -q, --quiet           suppress non-error output
  -o FILE, --output FILE
                        output signature to this file (default stdout)
  -u, --unique          keep only distinct signatures, removing duplicates (based on md5sum)
  -f, --force           try to load all files as signatures
  -k K, --ksize K       k-mer size; default=31
  --protein             choose a protein signature; by default, a nucleotide signature is used
  --no-protein          do not choose a protein signature
  --dayhoff             build Dayhoff-encoded amino acid signatures
  --no-dayhoff          do not build Dayhoff-encoded amino acid signatures
  --hp, --hydrophobic-polar
                        build hydrophobic-polar-encoded amino acid signatures
  --no-hp, --no-hydrophobic-polar
                        do not build hydrophobic-polar-encoded amino acid signatures
  --dna, --rna, --nucleotide
                        choose a nucleotide signature (default: True)
  --no-dna, --no-rna, --no-nucleotide
                        do not choose a nucleotide signature
  --picklist PICKLIST   select signatures based on a picklist, i.e. 'file.csv:colname:coltype'
  --picklist-require-all
                        require that all picklist values be found or else fail
```

**Comment by keyabarve** [comment]
@ctb When I added the `usage` for the `downsample` command in `src/sourmash/cli/sig/downsample.py`, and ran `sourmash sig downsample -h`, the text under `usage` did not print out.

**Comment by keyabarve** [comment]
@ctb I was not able to find the command line docs for the `ingest` and `manifest` commands. Could you guide me to where I could find them?

**Comment by ctb** [comment]
> @ctb I was not able to find the command line docs for the `ingest` and `manifest` commands. Could you guide me to where I could find them?

I think we probably don't have any. Could you make issues to add docs for these commands?

**Comment by keyabarve** [comment]
> > @ctb I was not able to find the command line docs for the `ingest` and `manifest` commands. Could you guide me to where I could find them?
> 
> I think we probably don't have any. Could you make issues to add docs for these commands?
>
Sure! I'll create 2 different issues.

**Comment by keyabarve** [comment]
@ctb I have added the required details for all the `sig` commands. Please review.

**Comment by ctb** [comment]
On Fri, Aug 13, 2021 at 09:47:40AM -0700, Keya Barve wrote:
> Sure! Should I create 2 separate issues?

Yep.

**Comment by keyabarve** [comment]
@ctb Please review.

**Comment by keyabarve** [comment]
@ctb Should this PR be closed/merged?

**Comment by ctb** [comment]
> @ctb Should this PR be closed/merged?

no, it just needs a lot of input from me, and I don't have time at the moment. No harm in leaving it open for now.

**Comment by keyabarve** [comment]
Alright, thanks!

**Comment by ctb** [comment]
notes to self for review:
- run each command with `-h` to see what it looks like
- verify markdown formatting is properly adjusted, and line lengths are ok

**Pull request merged**
