### PR TITLE
MRG: replace `lca_utils.LineagePair` with `tax_utils.LineagePair`

### PR DESCRIPTION
**Pull request by ctb**
Note: PR into https://github.com/sourmash-bio/sourmash/pull/2437

Wanted to try out the new code for myself!

### CODE REVIEW

**Comment by ctb** [comment]
No idea if the tests will all pass @bluegenes but enough of them did that I thought I'd make a PR out of it 😆

**Comment by ctb** [comment]
@bluegenes looks like all the tests pass!

**Review by bluegenes — APPROVED** [review]
lgtm -- thanks for making the new LineagePair work across the board!

**Comment by bluegenes** [comment]
whoops, misunderstood that this should have been merged into #2437 before merging that one into latest, sigh. Fixed conflicts (I think) and will merge this into latest next

**Comment by ctb** [comment]
> lgtm -- thanks for making the new LineagePair work across the board!

yes indeed it was a lot of work 😆 

> whoops, misunderstood that this should have been merged into #2437 before merging that one into latest, sigh. Fixed conflicts (I think) and will merge this into latest next

I didn't think - but yeah, that would probably have avoided the merge conflicts! :(

**Pull request merged**
