### PR TITLE
[MRG] simplify PR template

### PR DESCRIPTION
**Pull request by ctb**
This PR updates the GitHub PR template with the text below.

Ref https://github.com/dib-lab/sourmash/issues/834 

----

Please replace this text with:

* a brief description of your changes in this PR
* which issues this fixes in the issue tracker, if any ("Fixes #XXX")
* which issues this PR is related to, if any ("Ref #XXX")

Please also be sure to note here if file formats, command-line
interface, and/or the top-level sourmash API will change because of
this PR.

If you are a new contributor, please provide
[your ORCID](https://orcid.org).  If you don't have one, please
[register for one](https://orcid.org/register).

Once the items above are done, and all checks pass, request a review!

### CODE REVIEW

**Comment by ctb** [comment]
@keyabarve could you review this PR please? All you would need to do is check -

* the language makes sense to you
* the links in the changed markdown work (you can view it by going to the "Files changed..." tab above, or [go directly to the changed file](https://github.com/dib-lab/sourmash/blob/48f899003221d73ae89b92a9d5fb603f3197a492/.github/PULL_REQUEST_TEMPLATE.md))

**Comment by keyabarve** [comment]
@ctb I'm a little confused about what I need to do here. 
Should I replace the contents of the file "PULL_REQUEST_TEMPLATE.md" with the text mentioned above? Or should I keep the existing checklist and add the text above? Please clarify.

**Comment by ctb** [comment]
> @ctb I'm a little confused about what I need to do here.
> Should I replace the contents of the file "PULL_REQUEST_TEMPLATE.md" with the text mentioned above? Or should I keep the existing checklist and add the text above? Please clarify.

hi @keyabarve, no, in this case I'm asking you to look at the work _I've_ done and see if it makes sense to you - to do a change request review on my . You don't need to change or do anything other than look at my changes and see if they make sense to you (like I'm doing with your other pull request). Here's [a brief primer](http://willthames.github.io/2016/11/07/intro-to-code-reviews.html) if you're interested in more.

In this case, since it's not a set of changes to the code but rather to the pull request template, the code review is pretty minimal - you can just look at the template change and say "yes, that makes sense to me, and the link in the markdown text renders properly and links to a web page that exists."

If you agree that my change looks ok, you can just say "This looks good to me." which we often abbreviate to LGTM. If you would like some changes, you can add comments directly on the code (under the Files tab, above) or place a comment here.

**Comment by keyabarve** [comment]
@ctb I went over it and it looks good to me.

**Comment by ctb** [comment]
thank you!

**Pull request merged**
