### PR TITLE
[MRG] rationalize `SourmashSignature.name` and `str(sig)`

### LINKED ISSUE #566: Python API does not allow one to set names of sigs
Using the following code, I was trying to iterate over a set of samples and change the names in the signatures. Although this method successfully set the name in python land, when I wrote the signature back out, there was no name in the new signature. 

Talking with @luizirber, we think this should be the default behavior of the API. He thinks the rust implementation solves this.

```
from sourmash import signature

for i, row in mini.iterrows():
    file = row['SampleName'] + '.trinity_out_2.2.0.Trinity.fasta.renamed.fasta.sig'
    new_name  = row['ScientificName'] + " " + row['Strain'] + " " + row['SampleName']
    print(new_name)
    sigfp = open(file, 'rb')
    siglist = list(signature.load_signatures(sigfp))
    sig21 = siglist[0]
    sig21.name = new_name
    print(sig21.name)
    with open(('tmp/' + row['SampleName'] + '.sig'), 'wt') as fp:
        signature.save_signatures([sig21], fp)
```

### PR DESCRIPTION
**Pull request by ctb**
This PR simplifies and regularizes the `name` attribute on `SourmashSignature`. Briefly,

* `SourmashSignature.name` is now a property rather than a method; it is empty unless explicitly set during signature creation (or via rename).
* `SourmashSignature.__str__` now mimics the previous behavior of `name()`, by displaying the first non-empty property (name, filename, and finally md5sum).
* `SourmashSignature.__repr__` should be used in programmatic contexts (e.g. debugging, testing) only.

This affects the Python codebase pretty widely, because we (I, mostly) routinely conflated the first two uses. So much of the work of this PR was going through and figuring out which of the above to use :).

For migration,
* any place where user-consumed output is provided should switch from `sig.name()` to `str(sig)`.
* CSV etc output should formally differentiate between `sig.name`, `sig.filename`, and `sig.md5sum` where possible.
* in situations where the filename of a computed signature was implicitly relied upon and no name was set, signatures will need to be given a name explicitly.

Fixes #566.

TODO:
- [x] fix categorize output to use .name, etc.
- [x] fix index.py to use sig.name instead of str(sig)
- [x] fix lca classify to use sig.name instead of str(sig) in CSV output
- [x] fix lca summarize to use sig.name instead of str(sig) in CSV output
- [x] fix search_databases to use sig.name instead of str(sig) in CSV output

-----

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make coverage` Is the new code covered?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
notes to self -
- [x] write down difference between `sig.name`, `str(sig)`, etc.
- [x] figure out the right approach for `lca index` hack

**Comment by ctb** [comment]
and double check: do both sigs and minhashes have md5ums?

**Comment by ctb** [comment]
> and double check: do both sigs and minhashes have md5ums?

yes, but the Signature md5sum is the same as the minhash md5sum; the Python method on `SourmashSignature` just calls the minhash method directly, via Rust.

**Comment by ctb** [comment]
idle thought: I wonder if the default `.name` for a signature made by `compute` and `sketch` should be the filename?

**Comment by ctb** [comment]
- [ ] explore puzzling increase in precision for `test_sbt_categorize` (see #1180 for underlying cause!)

**Comment by ctb** [comment]
I think this is ready for a first pass, @luizirber. It's a bit of a mess but I think this PR goes a long way towards cleaning up the codebase. Not quite sure how to review it - I had to dig in to a lot of different parts of the code base :(

**Comment by luizirber** [comment]
the changes to `genome-s10+s11.sig` also broke the Rust test for loading signatures, it might be related to #1180...

**Comment by luizirber** [comment]
~~(maybe setup CI to run rust checks if files in `tests/test-data/` change?)~~ done in https://github.com/dib-lab/sourmash/pull/1179/commits/2e010e17e1c25d21ef26e97831e8005a3b80d179

**Comment by ctb** [comment]
On Fri, Aug 21, 2020 at 07:40:12AM -0700, Luiz Irber wrote:
> (maybe setup CI to run rust checks if files in `tests/test-data/` change?)

shouldn't CI be running the rust tests every time? but yes, that makes
sense to me.

**Comment by luizirber** [comment]
> On Fri, Aug 21, 2020 at 07:40:12AM -0700, Luiz Irber wrote: (maybe setup CI to run rust checks if files in `tests/test-data/` change?)
> shouldn't CI be running the rust tests every time? but yes, that makes sense to me.

I limited the Rust checks because.... it's a lot of jobs. The Rust code is still tested by proxy in Python, but I hadn't considered the case where the DATA used for tests changes.

**Comment by ctb** [comment]
> the changes to `genome-s10+s11.sig` also broke the Rust test for loading signatures, it might be related to #1180...

I'm confused - the test that is failing asks for there to be a single signature, but there have always been four sketches in this file. Maybe we're running afoul of the signature/sketches mismatch here, since I did a `sig rename` which loads and then saves, thus transforming it from "one signature with four sketches" to "four signatures with one sketch each.". Sigh. Umm, ok, I'll try to fix this test.

```
assert_eq!(sigs.len(), 1);
```

**Comment by ctb** [comment]
ok - fixed the last remaining WTF, caused by #1180.

**Comment by ctb** [comment]
bump @luizirber ;)

**Review by luizirber — APPROVED** [review]

**Pull request merged**
