### PR TITLE
final updates for 2024 JOSS publication

### PR DESCRIPTION
**Pull request by bluegenes**
- updates `CITATION.cff` as provided by JOSS
- updates README JOSS citation
- updates cli citation notice

### CODE REVIEW

**Comment by bluegenes** [comment]
@ctb ready for review

**Comment by ctb** [comment]
There's another two entries in README.md.

I'm assuming a release after this is a good idea? :) v4.8.10!!

**Comment by bluegenes** [comment]
> There's another two entries in README.md.

@ctb fixed, I think! 

> I'm assuming a release after this is a good idea? :) v4.8.10!!

sounds good to me

**Comment by ctb** [comment]
`test_citation_file` fails 😆 

I'll fix it if I get a chance.

**Pull request merged**
