### PR TITLE
[WIP] Add utility scripts for converting hash values to k-mers.

### PR DESCRIPTION
**Pull request by ctb**
Adds two utility scripts in `utils/`, `hashvals-to-signatures.py` and `signature-to-kmers.py`, for the purpose of converting hashes into k-mers.

`hashvals-to-signatures` takes a collection of hash values and turns them into a sourmash signature.

`signature-to-kmers` takes a signature and one or more sequence files, and outputs the k-mers that correspond to the hash values and the sequences that contain those k-mers.

Random musings -
* `hashvals-to-signatures` functionality could/should be added to `sourmash signature import/export` instead
* the `get_kmers_for_hashvals` function in `signature-to-kmers` is not very general. I think we should refactor some of the code in `_minhash.pyx` to expose a k-mer extraction function on MinHash objects, which would support a much more general function.

ref #483 

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make coverage` Is the new code covered?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
OK, I updated the scripts to be less clever :). I also added a script `utils/hashvals-to-kmers.py`.

The key function to look at (and you can use this directly in a notebook if you like...) is `get_kmers_for_hashvals(sequence, hashvals, ksize)`, which is hopefully self-explanatory in its use (but also has a docstring!!!!) This is a generator function that yields pairs of `kmer, hashval` for a given DNA sequence. Please let me know if they work better for you!

----

In terms of what went wrong before, I was not accounting for using 'num' minhashes, I think, and was assuming you were using scaled minhashes. Mea culpa. The latest code is less clever and should be more robust.

**Comment by phiweger** [comment]
@ctb so I'm testing this (yay!)

I would expect that if I calc the sig of some genome, and then use the hash2kmer script, to obtain the same number of kmers as the number of hash vals used in the sig.

```bash
sourmash compute -k 31 -n 100  GCF_000281435.2_ASM28143v2_genomic.fna.gz

python signature-to-kmers.py --output-kmers kmers.txt GCF_000281435.2_ASM28143v2_genomic.fna.gz.sig  GCF_000281435.2_ASM28143v2_genomic.fna.gz

# read 5767822 bp, found 56 kmers matching hashvals
```

Am I doing something wrong? I noticed that the number of returned kmers is roughly half the number of hash vals, which makes me suspect that there is a problem with canonical kmers -- do they "get lost" during backtranslation from hash to kmer?

**Comment by ctb** [comment]
Aaaaaand this is why I should always write tests, ladies and gentleman...

It was an issue of not being minimally clever, @olgabot - I wasn't choosing the correct canonical k-mer representation for reverse complements, so approximately 50% of the hashes were not being found.

Tested all three scripts like so:
```
sourmash compute -n 1000 data/GCF_000005845.2_ASM584v2_genomic.fna.gz -o test.sig  -k 31

utils/signature-to-kmers.py test.sig data/GCF_000005845.2_ASM584v2_genomic.fna.gz --output-kmers=test.csv

utils/hashvals-to-kmers.py test.hashes.txt data/GCF_000005845.2_ASM584v2_genomic.fna.gz --output-kmers=test2.csv

utils/hashvals-to-signature.py test.hashes.txt -k 31 -o test3.sig
utils/signature-to-kmers.py test3.sig data/GCF_000005845.2_ASM584v2_genomic.fna.gz --output-kmers=test3.csv
```
and got identical output yielding all 1,000 k-mers.

**Comment by ctb** [comment]
@olgabot it sounds like this works for you. @luizirber any object to me merging this and creating issues for:

* adding `hashvals-to-signatures` functionality to `sourmash signature import/export` instead
* generalizing the `get_kmers_for_hashvals` function in `signature-to-kmers` by refactoring some of the code in `_minhash.pyx` to expose a k-mer extraction function on MinHash objects

?

**Comment by taylorreiter** [comment]
I just tried utils/hashvals-to-signature.py. It ran almost instantaneously on a file with 10 hashes, but it never finished after running for 24 hours on a file with 48 million hashes. I'm trying it now with 9 million instead and hoping for a slightly faster run time.

**Comment by taylorreiter** [comment]
For 9 million hashes, the run time was 7 hours.

**Comment by ctb** [comment]
just to confirm: you ran hashvals-to-signature, not signature-to-kmers?

I have to say at that scale I'm ok with a custom solution :). I was not thinking of signatures with millions of hashes when we designed... well, any of sourmash!

**Comment by ctb** [comment]
...but the good news is we can cannibalize code from those scripts now that we know they works properly...

**Comment by taylorreiter** [comment]
yes! I ran `hashvals-to-signature.py`! I wanted to filter all hashes that had abundance 1 across 1000 data sets -- filtering all abundance 1 hashes would have removed some real hashes, but if they were abundance 1 across the entire dataset, they were more likely to be errors. 

Originally, I generated a set of all abundance 1 hashes across the data set -- this was 48 million hashes (scaled 2000, k 31). I was going to use `sourmash siganture subtract` with this, but it took too long to convert to a signature.  https://github.com/taylorreiter/ibd/blob/master/sandbox/get_low_count_hashes.ipynb

Then, I decided to make a set of all hashes greater than abundance 1. This was 9 million hashes, and I used `sourmash signature intersect` to retain only these hashes in each sample-specific signature. https://github.com/taylorreiter/ibd/blob/master/sandbox/get_greater_than_1_count_hashes.ipynb

Cannibalize away :)

**Comment by luizirber** [comment]
> @luizirber any object to me merging this and creating issues for:
> 
>     * adding `hashvals-to-signatures` functionality to `sourmash signature import/export` instead
> 
>     * generalizing the `get_kmers_for_hashvals` function in `signature-to-kmers` by refactoring some of the code in `_minhash.pyx` to expose a k-mer extraction function on MinHash objects

In fine with this plan. Is this ready for review and merge (despite the `[WIP]` in the title), @ctb?

**Comment by ctb** [comment]
there aren't any tests, tho. and it's not integrated into sourmash. so...
concerned about that.

On Thu, Nov 21, 2019 at 04:27:37PM -0800, Luiz Irber wrote:
> > @luizirber any object to me merging this and creating issues for:
> > 
> >     * adding `hashvals-to-signatures` functionality to `sourmash signature import/export` instead
> > 
> >     * generalizing the `get_kmers_for_hashvals` function in `signature-to-kmers` by refactoring some of the code in `_minhash.pyx` to expose a k-mer extraction function on MinHash objects
> 
> In fine with this plan. Is this ready for review and merge (despite the `[WIP]` in the title), @ctb?
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/sourmash/pull/724#issuecomment-557333360
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by luizirber** [comment]
> there aren't any tests, tho. and it's not integrated into sourmash. so... concerned about that.

Fair point. Since it doesn't touch anything that is actually changing with #424, I won't worry about merging this soon.

**Comment by ctb** [comment]
Would be massively sped up by https://github.com/dib-lab/sourmash/issues/1214

**Comment by ctb** [comment]
see https://github.com/sourmash-bio/sourmash/pull/1695

**Comment by ctb** [comment]
closing in favor of https://github.com/sourmash-bio/sourmash/pull/1695.

**Pull request closed without merging**
