### PR TITLE
MRG: fix output for `sketch ... --singleton`

### LINKED ISSUE #2819: output reporting on `sourmash sketch dna --singleton ...` is borked
```
sourmash sketch dna --singleton podar-ref/*.fa -o podar-ref-singleton.zip
...
calculated 60 signatures for 1 sequences in podar-ref/39.fa
calculated 61 signatures for 1 sequences in podar-ref/4.fa
calculated 62 signatures for 1 sequences in podar-ref/40.fa
calculated 63 signatures for 1 sequences in podar-ref/41.fa
calculated 64 signatures for 1 sequences in podar-ref/42.fa
calculated 65 signatures for 1 sequences in podar-ref/43.fa
calculated 67 signatures for 2 sequences in podar-ref/44.fa
calculated 68 signatures for 1 sequences in podar-ref/45.fa
calculated 69 signatures for 1 sequences in podar-ref/46.fa
calculated 71 signatures for 2 sequences in podar-ref/47.fa
calculated 72 signatures for 1 sequences in podar-ref/48.fa
calculated 300 signatures for 228 sequences in podar-ref/49.fa
calculated 301 signatures for 1 sequences in podar-ref/5.fa
calculated 302 signatures for 1 sequences in podar-ref/50.fa
calculated 303 signatures for 1 sequences in podar-ref/51.fa
calculated 304 signatures for 1 sequences in podar-ref/52.fa
calculated 305 signatures for 1 sequences in podar-ref/53.fa
calculated 306 signatures for 1 sequences in podar-ref/54.fa
calculated 307 signatures for 1 sequences in podar-ref/55.fa
calculated 308 signatures for 1 sequences in podar-ref/56.fa
calculated 309 signatures for 1 sequences in podar-ref/57.fa
calculated 339 signatures for 30 sequences in podar-ref/58.fa
calculated 344 signatures for 5 sequences in podar-ref/59.fa
calculated 420 signatures for 76 sequences in podar-ref/6.fa
calculated 431 signatures for 11 sequences in podar-ref/60.fa
calculated 478 signatures for 47 sequences in podar-ref/61.fa
calculated 479 signatures for 1 sequences in podar-ref/62.fa
calculated 483 signatures for 4 sequences in podar-ref/63.fa
calculated 486 signatures for 3 sequences in podar-ref/7.fa
calculated 487 signatures for 1 sequences in podar-ref/8.fa
calculated 490 signatures for 3 sequences in podar-ref/9.fa
saved 490 signature(s) to 'podar-ref-singleton.zip'. Note: signature license is CC0.
```

### PR DESCRIPTION
**Pull request by ctb**
Fixes https://github.com/sourmash-bio/sourmash/issues/2819

### CODE REVIEW

**Comment by ctb** [comment]
Ready for review & merge @sourmash-bio/devs

**Review by bluegenes — APPROVED** [review]
Is there a check you could add to a test to get those lines covered?

otherwise lgtm

**Comment by ctb** [comment]
> Is there a check you could add to a test to get those lines covered?

added test for this PR in 0ed05db.

**Comment by ctb** [comment]
> Is there a check you could add to a test to get those lines covered?

the line _is_ executed by the tests - multiple different tests - but it's not showing up in code coverage. 🤷

**Pull request merged**
