### PR TITLE
MRG: update README with repostatus and pyver badges, and Windows support

### LINKED ISSUE #2909: add repostatus badge to README
per [review](https://github.com/pyOpenSci/software-submission/issues/129#issuecomment-1870572982)

we are missing:
>A [repostatus.org](https://www.repostatus.org/) badge,

### LINKED ISSUE #2910: add badges for python versions supported
per [review](https://github.com/pyOpenSci/software-submission/issues/129#issuecomment-1870572982)

### PR DESCRIPTION
**Pull request by ctb**
Direct link to updated README: [link](https://github.com/sourmash-bio/sourmash/blob/update_readme/README.md)

Adds repostatus badge as well as list of python versions supported.

Switches to recommending conda-forge and sourmash-minimal, since that supports Windows ref #1923.

Also adds direct mention of operating systems supported, including Windows (ref https://github.com/sourmash-bio/sourmash/issues/1923).

Fixes https://github.com/sourmash-bio/sourmash/issues/2909
Fixes https://github.com/sourmash-bio/sourmash/issues/2910

### CODE REVIEW

**Comment by ctb** [comment]
@luizirber I just noticed this in the README -

>Please note that this repository is participating in a study into sustainability of open source projects. Data will be gathered about this repository for approximately the next 12 months, starting from 2021-06-11.

etc. Should I remove this now? The thesis etc is all written... [ref](https://sustainable-open-science-and-software.github.io/).

**Comment by ctb** [comment]
hey @sourmash-bio/devs anything else we should add to the README? thx

**Comment by ccbaumler** [comment]
Do you want to update line 85 as well? `source` to `conda`?

**Comment by ctb** [comment]
> Do you want to update line 85 as well? `source` to `conda`?

thanks!!

**Comment by ctb** [comment]
hmmm.. should we change install to reference sourmash-minimal, per https://github.com/sourmash-bio/sourmash/issues/1923?

**Comment by ctb** [comment]
Ready for review and merge @sourmash-bio/devs !

**Comment by ccbaumler** [comment]
Most links work for me except for the lab website link. For some reason, the link is trying to use https instead of http (which is the written link).

> http://ivory.idyll.org/lab/ is changing to https://ivory.idyll.org/lab/ in address bar

What is the explicit reason for the following paragraph:
> For more information, please visit our informational page or download our participant information sheet.

Is it a project collecting sourmash use information (anonymously)?

**Comment by ctb** [comment]
> Most links work for me except for the lab website link. For some reason, the link is trying to use https instead of http (which is the written link).
> 
> > http://ivory.idyll.org/lab/ is changing to https://ivory.idyll.org/lab/ in address bar

yeah, that's a thing your browser is doing. I'll try to figure out how to get https working on that site, but not just for the PR ;).

> What is the explicit reason for the following paragraph:
> 
> > For more information, please visit our informational page or download our participant information sheet.
> 
> Is it a project collecting sourmash use information (anonymously)?

I just removed this - it was part of a research thing-y that I asked about above.

**Comment by ctb** [comment]
(I'm going to merge once tests pass again)

**Pull request merged**
