### PR TITLE
[EXP] Make wasm features more JS-like

### LINKED ISSUE #1622: sourmash_bg missing in npm package
Hey there,
I just did an `npm i sourmash` which installs the latest version `0.10.0` but when I'm trying to use it I get an error: 
> `node_modules/sourmash/sourmash_bg.js doesn't exist`

I look around the published packages and the change comes from version 0.7.0 onwards. The file `sourmash.js` tries to use the `sourmash_bg.js` but the file is not in the package. As you can see here: https://www.jsdelivr.com/package/npm/sourmash?version=0.10.0

On version 0.6.0, there is not mention of that file. Am I missing something, like a webpack configuration, or indeed the file is missing in the published package

### PR DESCRIPTION
**Pull request by luizirber**
Fixes #1622 

The current sourmash [NPM package](https://www.npmjs.com/package/sourmash) is a direct upload from the results of `wasm-pack` and is not very ergonomic for direct usage in JS. The [arrow-wasm](https://github.com/domoritz/arrow-wasm/) project does something else, opting for wrapping the `wasm-pack` output into a more palatable JS package. So I'm trying the same approach here =]

This means removing the `src/core/src/wasm.rs` file and moving most of the wasm parts into `src/wasm`, a new Rust crate with the code to make a nice JS package.

ping @gustavo-salazar, once I have something more complete can we review together how the JS API looks like (and how to test in a way that doesn't break in the future for you)?

# TODO

- [ ] bump version of the Rust crate
- [ ] add a CI check to guarantee that the Rust/wasm/JS versions are synced
- [ ] `src/wasm/lib.rs` has some commented code because we can't do a `impl` for types defined outside the crate (since now they tread `sourmash` as a third-party dep. Need to either create a newtype and dispatch calls to the sourmash types, or something like that.

### CODE REVIEW

**Comment by luizirber** [comment]
@gustavo-salazar: I started generating packages for the new sourmash version, they are contained in the [Artifacts](https://github.com/sourmash-bio/sourmash/actions/runs/971897514#artifacts) section for each CI run. (annoyingly, there is a `.tgz` file which is the NPM package inside the `artifact.zip` file...)

I tried to use it with https://github.com/EBI-Metagenomics/mgnify-sourmash-component but had issues because webpack is not copying the wasm file to the proper place. The package is also missing the `.d.ts` file, working on fixing it. Can you take a look if you have some time? =]

**Comment by luizirber** [comment]
Reconsidering this approach (hence the new `[EXP]` tag).

## Current solution (building the NPM package directly from `core`):

Benefits:
- Earlier detection of things that might not work in `wasm` (because it will fail compilation)
- Access to `pub(crate)` methods, can depend on methods we might not want to expose in the public API (this can be a drawback too)

Drawbacks:
- Need to annotate which methods to export (with `#[wasm_bindgen]`), which polutes a lot the `core` crate.
- Limit the types of parameters in functions to values that can be passed from Wasm to JS (needing to annotate even more types around the crate)
  * I ended up created some "shims" around the real Rust method because of that...

## Solution in this PR

Benefits:
- Cleaner API for JS users: we can pull more types from `web_sys` without conflicting with the `core` methods (they still act as shims, tho)
- Clean up the `core` crate: a lot of annotations (the `#[wasm_bindgen]` stuff) can be removed, since they are declared in the `wasm` crate now.

Drawbacks:
- Using the `arrow-wasm` approach led to issues with properly using `rollup` to package everything (like missing the `.d.ts` files)
- It is a separate crate, so depends more on CI to make sure everything is tested/synchronized with original `core` code
- It redeclares types, much like what happens in Python (the `MinHash` class in Python, for example)
- Implementation can only use public methods in `core` (this can also be a benefit)

## Proposed plan

Short term, fix the current package in #1643 and release a new package to NPM.

In the medium/long term, do the approach in this PR (separate `wasm` crate) but without using `rollup` for packaging (so, removing parts of the `arrow-wasm` approach). Slowly expand the JS API as needed for [MGNify sourmash component](https://github.com/EBI-Metagenomics/mgnify-sourmash-component). This includes using `needletail` for FASTA/Q parsing (take a [`File`](https://docs.rs/web-sys/0.3.51/web_sys/struct.File.html) in the JS API and do everything in Rust, instead of parsing sequences in JS like it is now) and `niffler` for working with compressed files.

**Comment by gustavo-salazar** [comment]
Hey @luizirber 
I did a quick test, taking the artifact and using `npm link`, I also copied the types files in the folder just to avoid that sort of issues. 
It seems to be working OK, I'm able to generate the sketches.

I had to add `url` as dependency and use the ProvidePlugin to make it available via webpack. After that it worked

**Comment by luizirber** [comment]
Closing in favor of #1643

**Pull request closed without merging**
