### PR TITLE
[MRG] remove `LazyLoadedIndex`

### LINKED ISSUE #1905: consider removing `LazyLoadedIndex`
per @bluegenes [comment](https://github.com/sourmash-bio/sourmash/pull/1891#discussion_r836766553) `LazyLoadedIndex` seems to provide only a subset of the functionality in `StandaloneManifestIndex`; consider removing.

It is not used in any of the core sourmash code. 🤷

### PR DESCRIPTION
**Pull request by ctb**
Removes the `LazyLoadedIndex` class, which is (a) unused and (b) replaced more generically with `StandaloneManifestIndex`.

Fixes https://github.com/sourmash-bio/sourmash/issues/1905

### CODE REVIEW

**Comment by ctb** [comment]
Ready for review & merge @sourmash-bio/devs!

**Comment by ccbaumler** [comment]
Is `LazyLoadedIndex` being removed because of redundancy as well as its unused status? 

> To quote CTB:
> "CTB: This may be redundant with StandaloneManifestIndex."?

**Comment by ctb** [comment]
yep - is that something that needs to be made more clear? I think it's covered in the issue and the PR description both (see point (b)) but happy to expand.

(If there's any remaining place where we reference `LazyLoadedIndex` in the codebase, we should remove that. I don't think there is, but I might have missed one.)

**Comment by ccbaumler** [comment]
> yep - is that something that needs to be made more clear? I think it's covered in the issue and the PR description both (see point (b)) but happy to expand.

No, I think it's pretty clear now 😆 . I did not think to check the issue the PR was created from.

> 
> (If there's any remaining place where we reference `LazyLoadedIndex` in the codebase, we should remove that. I don't think there is, but I might have missed one.)

To double-check, I ran `git grep -rn LazyLoadedIndex` to compare line number with those removed. Looks like you got them all.
```
baumlerc@farm:~/sourmash$ git grep -rn LazyLoadedIndex
src/sourmash/index/__init__.py:34:LazyLoadedIndex - selection on manifests with loading of index on demand.
src/sourmash/index/__init__.py:465:      store signatures in memory, see LazyLoadedIndex.
src/sourmash/index/__init__.py:1061:class LazyLoadedIndex(Index):
src/sourmash/index/__init__.py:1078:            raise ValueError(f"'{filename}' must exist when creating LazyLoadedIndex")
src/sourmash/index/__init__.py:1171:        return LazyLoadedIndex(self.filename, new_manifest)
src/sourmash/index/__init__.py:1194:    This class overlaps in concept with LazyLoadedIndex and behaves
src/sourmash/index/__init__.py:1196:    on-disk Index object.  However, unlike LazyLoadedIndex, this class
tests/test_index.py:2268:    # some basic tests for LazyLoadedIndex
tests/test_index.py:2273:        db = index.LazyLoadedIndex.load(lcafile)
tests/test_index.py:2280:    db = index.LazyLoadedIndex.load(test_zip)
tests/test_index.py:2301:    # some basic tests for LazyLoadedIndex that is empty
tests/test_index.py:2307:    db = index.LazyLoadedIndex.load(test_zip)
tests/test_index.py:2330:    db = index.LazyLoadedIndex.load(test_zip)
tests/test_index.py:2349:        index.LazyLoadedIndex(runtmp.output('xyz'), True)
tests/test_index.py:2359:        index.LazyLoadedIndex(sig2, None)
tests/test_index_protocol.py:12:                            StandaloneManifestIndex, LazyLoadedIndex)
tests/test_index_protocol.py:156:    return LazyLoadedIndex(outfile, mf)
```

**Review by ccbaumler — APPROVED** [review]
LGTM

**Comment by ctb** [comment]
> > (If there's any remaining place where we reference `LazyLoadedIndex` in the codebase, we should remove that. I don't think there is, but I might have missed one.)
> 
> To double-check, I ran `git grep -rn LazyLoadedIndex` to compare line number with those removed. Looks like you got them all.

cool - note you can do:

```
git fetch
git switch dk_remove_lazyindex
```

to actually switch to this branch, so you don't need to do the stuff manually.

**Pull request merged**
