### PR TITLE
MRG: update JOSS for sourmash v4

### PR DESCRIPTION
**Pull request by bluegenes**
Minor updates to JOSS paper for v4:
  - [x] update title with 'v4'
  - [x] update authors
  - [x] update funding

### CODE REVIEW

**Comment by ctb** [comment]
We will want to add to funding:

- PIG-PARADIGM grant from Novo Nordisk
- NSF genomeRxiv

and I think that's it?

**Comment by bluegenes** [comment]
genomeRxiv is NSF #2018522

**Comment by ctb** [comment]
"PIG-PARADIGM (Preventing Infection in the Gut of developing Piglets–and thus Antimicrobial Resistance – by disentAngling the interface of DIet, the host and the Gastrointestinal Microbiome) from the Novo Nordisk Foundation to CTB."

**Comment by bluegenes** [comment]
@ctb @luizirber ready for review

**Review by ctb — APPROVED** [review]

**Review by luizirber — APPROVED** [review]

**Pull request merged**
