### PR TITLE
[EXP] add a `prefetch` linear search function to `Index`

### PR DESCRIPTION
**Pull request by ctb**
NOTE: PR into https://github.com/dib-lab/sourmash/pull/1370.

This PR adds:
* a `--prefetch` option (currently defaulting to True) to `sourmash gather` CLI
* a `prefetch` generator method on `Index` that does the linear search from #1370/greyhound/etc.

See [comment on #1370](https://github.com/dib-lab/sourmash/pull/1370#issuecomment-791998818)  for motivation.

## Checklist

- [ ] Is it mergeable?
- [ ] `make test` Did it pass the tests?
- [ ] `make coverage` Is the new code covered?
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
Fun fact!! When turning `sourmash gather --prefetch` on by default, almost all of the tests pass!

The two that don't pass are -
* `test_gather_csv`, because I don't properly track where the signature came from (ref https://github.com/dib-lab/sourmash/issues/810#issuecomment-652519225)
* `gather_query_downsample` because, unlike in normal `gather`, I don't downsample the _query_ appropriately with prefetch. This is actually questionable behavior to my thinking. I added a new test that checks for what I think is the right behavior, and left this one failing on this PR for now.

**Comment by ctb** [comment]
Legend has it that @luizirber will soon come place a comment on here about how `prefetch(...)` is `Index.find` with `search_containment` as the search function.

This appears to be accurate, with one exception: the `find(...)` function is currently not a generator, but `prefetch` is.  I change `find` to a generator in 70168f1c, and will refactor accordingly.

**Comment by luizirber** [comment]
> Legend has it that @luizirber will soon come place a comment on here about how `prefetch(...)` is `Index.find` with `search_containment` as the search function.
> 
> This appears to be accurate, with one exception: the `find(...)` function is currently not a generator, but `prefetch` is. I change `find` to a generator in [70168f1](https://github.com/dib-lab/sourmash/commit/70168f1cfcf1ce1b567b5e59ac4dd802cafd6a92), and will refactor accordingly.

I not sure they are the same same, but it sure feels like `prefetch`, `Index.find`, `Index.filter` and `Index.select` are very similar. Can we implement them in terms of each other in the base `Index` class? This way it is available for each implementation to override with a more efficient version, but we avoid having to implement all of them for each index implementation.

**Comment by ctb** [comment]
> I not sure they are the same same, but it sure feels like `prefetch`, `Index.find`, `Index.filter` and `Index.select` are very similar. Can we implement them in terms of each other in the base `Index` class? This way it is available for each implementation to override with a more efficient version, but we avoid having to implement all of them for each index implementation.

absolutely agree (I assume you mean prefetch/find and filter/select).

**Comment by ctb** [comment]
merged into #1370.

**Pull request merged**
