### PR TITLE
[MRG]  Update tests to use `runtmp` fixture instead of `utils.TempDirectory()`

### LINKED ISSUE #1386: update tests to use `runtmp` fixture instead of `utils.TempDirectory()`
(This is a "repeatable quest" issue that involves many small changes; it's good for people looking for a good first issue, or second issue, to go through our contribution pipeline.)

Many of our tests under `tests/` use the following syntax to place things in a temporary directory that will get cleaned up at the end of the test run:

```
def test_plot_override_labeltext():
    with utils.TempDirectory() as location:
        ...
        status, out, err = utils.runscript('sourmash', ..., in_directory=location)
```

This can be replaced with the newer, cleaner and more concise (less indentation!) syntax:

```
@utils.in_tempdir
def test_plot_override_labeltext(c):
    c.run_sourmash('...')
   status, out, err = c.last_result.status, c.last_result.out, c.last_result.err
```

For this repeatable quest, please refactor any three tests to use the newer syntax.

### PR DESCRIPTION
**Pull request by keyabarve**
Partly fixes #1386

Changes `utils.TempDirectory()` to `runtmp` in tests.

TODO items:
- [x] remove (or move) the .sbt.v3 files that are committed on this PR
- [x] `test_sourmash.py::test_do_sourmash_sbt_move_and_search_output` still uses runscript; intentional?
- [x] address `test_do_sourmash_sketchdna_with_bad_scaled` duplicate test
- [x] address `test_do_sketch_with_seed` duplicate test

### CODE REVIEW

**Comment by keyabarve** [comment]
@ctb I have a few questions:
- I tried changing one test: `tests/test_sourmash.py::test_plot_override_labeltext`, but there is a line in it: `with open(os.path.join(location, 'new.labels.txt'), 'wt') as fp:`, which is giving an error since `location` isn't defined anymore. I'm not sure how to change this particular line. There are also quite a few tests in which `location` is used in different places. Could you provide any hints on how to fix this? 

- Also, in the command: 
```
   status, out, err = utils.runscript('sourmash',
                                        ['compare'] + inp_sigs +
                                        ['-o', 'cmp', '-k', '21', '--dna'],
                                        in_directory=location)
```
there is `+ inp_sigs +` which I'm not sure how to change, so I wrote the command this way:
```
runtmp.sourmash('compare', inp_sigs, '-o', 'cmp', '-k', '21', '--dna')
```
Is this correct? If not, how can I fix it?

**Comment by keyabarve** [comment]
Another test is failing: `tests/test_sourmash.py::test_compare_no_choose_molecule_fail` and this is the error: 
```
>           raise SourmashCommandFailed(self.last_result.err)
multiple molecule types loaded; please specify --dna, --protein

tests/sourmash_tst_utils.py:195: SourmashCommandFailed
```
I'm not being able to fix this. Should I be doing a `with pytest.raises(SourmashCommandFailed)` code block?

**Comment by keyabarve** [comment]
Some tests in which `sketch` is done twice, are failing and these are examples of the errors:
The test is: `tests/test_sourmash.py::test_do_sourmash_index_multimol_fail`
```        if self.last_result.status:
>           raise SourmashCommandFailed(self.last_result.err)
loading 2 files into SBT
multiple k-mer sizes or molecule types present; fail.
specify --dna/--protein and --ksize as necessary
ksizes: 10, 30; moltypes: protein

tests/sourmash_tst_utils.py:195: SourmashCommandFailed
```

The test is: `tests/test_sourmash.py::test_do_sourmash_index_multiscaled_fail`
```
        if self.last_result.status:
>           raise SourmashCommandFailed(self.last_result.err)
loading 2 files into SBT
trying to build an SBT with incompatible signatures.
nums = {0}; scaleds = {1, 10}

tests/sourmash_tst_utils.py:195: SourmashCommandFailed
```

**Comment by keyabarve** [comment]
@ctb Please review.

**Comment by keyabarve** [comment]
@ctb Some of the tests here are failing and they all have the same error, that is,  I'm facing the same issue with all of them. There are certain lists of strings that are called in the command, which I'm not being able to change to `runtmp` command. For example, in `test_do_sourmash_sbt_combine`, the command that I'm trying to change is:
```
status, out, err = utils.runscript('sourmash',
                                        ['index', '-k', '31', 'zzz'] + files,
                                        in_directory=location)
```
where `files = [utils.get_test_data(f) for f in utils.SIG_FILES]` is a list of strings. I'm trying to write the command in this way:
`runtmp.sourmash('index', '-k', '31', 'zzz', ", ".join(files))`, but it still gives me an error. I'm not sure how to fix this. Could you provide any hints?

**Comment by ctb** [comment]
> @ctb Some of the tests here are failing and they all have the same error, that is, I'm facing the same issue with all of them. There are certain lists of strings that are called in the command, which I'm not being able to change to `runtmp` command. For example, in `test_do_sourmash_sbt_combine`, the command that I'm trying to change is:
> 
> ```
> status, out, err = utils.runscript('sourmash',
>                                         ['index', '-k', '31', 'zzz'] + files,
>                                         in_directory=location)
> ```
> 
> where `files = [utils.get_test_data(f) for f in utils.SIG_FILES]` is a list of strings. I'm trying to write the command in this way:
> `runtmp.sourmash('index', '-k', '31', 'zzz', ", ".join(files))`, but it still gives me an error. I'm not sure how to fix this. Could you provide any hints?

Right - try `*files` instead of `",".join(files)`. Apparently it's called a splat operator!? :)

https://stackoverflow.com/questions/7745952/how-to-expand-a-list-to-function-arguments-in-python

**Comment by keyabarve** [comment]
> Right - try `*files` instead of `",".join(files)`. Apparently it's called a splat operator!? :)
> 
> https://stackoverflow.com/questions/7745952/how-to-expand-a-list-to-function-arguments-in-python
> 
Alright, thanks! It worked!

**Comment by keyabarve** [comment]
@ctb There are a few tests that are failing with the same error, for example, in `tests/test_sourmash.py::test_migrate`, there is this line: 
```
shutil.copytree(os.path.join(os.path.dirname(testdata), '.sbt.v3'),
                    os.path.join('.sbt.v3'))
``` 
which I have written as: 
```
shutil.copytree(runtmp.output(os.path.dirname(testdata), '.sbt.v3'),
                    runtmp.output('.sbt.v3'))
```
and I'm getting this error: ` TypeError: output() takes 2 positional arguments but 3 were given`. I'm not sure how to fix this. Could you provide some hints?

**Comment by ctb** [comment]
right, runtmp.output only takes one argument.

I recommend putting in some print statements to figure out what
the paths are before you change them, and then verify that you're
making the same after you start using runtmp.

On Mon, Aug 23, 2021 at 02:58:05PM -0700, Keya Barve wrote:
> @ctb There are a few tests that are failing with the same error, for example, in `tests/test_sourmash.py::test_migrate`, there is this line: 
> ```shutil.copytree(os.path.join(os.path.dirname(testdata), '.sbt.v3'),
>                     os.path.join('.sbt.v3'))``` 
> which I have written as: 
> ```shutil.copytree(runtmp.output(os.path.dirname(testdata), '.sbt.v3'),
>                     runtmp.output('.sbt.v3'))```
> and I'm getting this error: ` TypeError: output() takes 2 positional arguments but 3 were given`. I'm not sure how to fix this. Could you provide some hints?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/sourmash-bio/sourmash/pull/1718#issuecomment-904161010
-- 
C. Titus Brown, ***@***.***

**Comment by keyabarve** [comment]
@ctb I figured out my mistake and was able to fix it! Please review.

**Comment by keyabarve** [comment]
I am trying to change the tests in `tests/test_sbt.py` as well, but one of the tests: `test_sbt_fsstorage` is failing. There is a line:
`with FSStorage(location, '.fstree') as storage:` which I'm trying to change to: `with runtmp.output.FSStorage('.fstree') as storage:`, but it is failing with this error: `AttributeError: 'function' object has no attribute 'FSStorage'`. I have also tried doing this: `with runtmp.output('.fstree')`, but that gives an error too: `AttributeError: __enter__`. Could you provide some hints on how to fix this?

**Comment by keyabarve** [comment]
@ctb I have changed all of the tests to use `runtmp` except for the ones in `tests/test_sourmash_compute.py` since `compute ` is going to be removed. Should I still change these tests to use `runtmp`?

**Comment by ctb** [comment]
On Wed, Aug 25, 2021 at 11:25:32AM -0700, Keya Barve wrote:
> @ctb I have changed all of the tests to use `runtmp` except for the ones in `tests/test_sourmash_compute.py` since `compute ` is going to be removed. Should I still change these tests to use `runtmp`?

no, good catch!

**Comment by keyabarve** [comment]
Alright! Thanks!

**Comment by keyabarve** [comment]
There is also another test: `tests/test_sourmash.py::test_storage_convert` that is failing on the PR but not failing on my computer. I'm not sure why this is happening and how I can fix it. Also, this test: `tests/test_sbt.py:: test_sbt_fsstorage` is failing and I'm not sure how to fix it.

**Comment by ctb** [comment]
> There is also another test: `tests/test_sourmash.py::test_storage_convert` that is failing on the PR but not failing on my computer. I'm not sure why this is happening and how I can fix it. Also, this test: `tests/test_sbt.py:: test_sbt_fsstorage` is failing and I'm not sure how to fix it.

hi keya, go ahead and merge #1724 to fix `test_sbt_fsstorage`!

in re `tests/test_sourmash.py::test_storage_convert`, you would need to have IPFS installed to test this. I suggest simply reverting your changes to that test and creating a new issue pointing out that this needs conversion.

**Comment by keyabarve** [comment]
@ctb There seem to be some conflicts here and I'm not sure how to resolve them. Could you provide some suggestions?

**Comment by ctb** [comment]
> @ctb There seem to be some conflicts here and I'm not sure how to resolve them. Could you provide some suggestions?

are you unsure of how to resolve them procedurally (like, how to use git in this instance?) or are you unsure of what the right resolution is in the code?

if it's the latter, aren't you are the author of the changed code? You just need to go through and figure out what the code should look like according to the changes you made.

**Comment by keyabarve** [comment]
I'm not sure how to resolve them procedurally. Should I just click on the "resolve conflicts" tab and delete the code that is not necessary?

**Comment by ctb** [comment]
ok - here are two tutorials,

https://www.atlassian.com/git/tutorials/using-branches/merge-conflicts

https://www.simplilearn.com/tutorials/git-tutorial/merge-conflicts-in-git

that might help.

**Comment by keyabarve** [comment]
alright, i'll check them out. thanks!

**Comment by keyabarve** [comment]
@ctb When I was resolving the conflicts, I realized that there were 2 new tests written that were still using `utils.TempDirectory()`, so I changed them, but one of those tests is failing and I can't seem to figure out what the error is. There is also one additional pre-existing test that is now failing, and I can't understand that error either.

**Comment by keyabarve** [comment]
Could you provide some hints/suggestions on how to fix this?

**Comment by ctb** [comment]
it looks like the test `test_do_sketch_protein_multik_input_from_file` is testing something completely different in `latest` than it is in this PR, which is Bad. Please revisit that one.

**Comment by ctb** [comment]
(it looks like you copied the code from `test_do_sourmash_sketchdna_with_scaled_2` in instead)

**Comment by ctb** [comment]
Other than that, all of the remaining failed tests on this branch seem to be because you changed the error messages output by sourmash, but didn't change the test code.

**Comment by ctb** [comment]
As a side note, this PR is going to be very hard to review; there are a lot of indentation changes so the diffs aren't very useful for comparing code to catch mistakes like the one with `test_do_sketch_protein_multik_input_from_file`.

In the future, if you're changing tests, let's try to use one PR for every 3-4 tests, please ;).

**Comment by keyabarve** [comment]
> (it looks like you copied the code from `test_do_sourmash_sketchdna_with_scaled_2` in instead)
>
Oh okay.

**Comment by keyabarve** [comment]
> As a side note, this PR is going to be very hard to review; there are a lot of indentation changes so the diffs aren't very useful for comparing code to catch mistakes like the one with `test_do_sketch_protein_multik_input_from_file`.
> 
Oh right, I'm sorry about that!

> In the future, if you're changing tests, let's try to use one PR for every 3-4 tests, please ;).
>
Yes, for sure!

**Comment by keyabarve** [comment]
@ctb Please review.

**Comment by keyabarve** [comment]
@ctb Ready for review and merge!

**Comment by keyabarve** [comment]
@ctb Ready for review and merge!

**Comment by ctb** [comment]
Working on reviewing; it's a pretty large PR so 🤷

**Comment by ctb** [comment]
Hi @keyabarve I'm still working through the (many, many :) changes, but here are a few things you could dig into while I'm finishing the review.

First, I noticed that you added some new files in this PR. Was this intentional, and if so, why?
```
.sbt.v3/0107d767a345eff67ecdaed2ee5cd7ba |  522 +++++++++++
 .sbt.v3/4e94e60265e04f0763142e20b52c0da1 |  522 +++++++++++
 .sbt.v3/60f7e23c24a8d94791cc7a8680c493f9 |  522 +++++++++++
 .sbt.v3/6d6e87e1154e95b279e5e7db414bc37b |  522 +++++++++++
 .sbt.v3/b59473c94ff2889eca5d7165936e64b3 |  522 +++++++++++
 .sbt.v3/f0c834bc306651d2b9321fb21d3e8d8f |  522 +++++++++++
 .sbt.v3/f71e78178af9e45e6f1d87a0c53c465c |  522 +++++++++++
 .sbt.v3/internal.0                       |  Bin 0 -> 50042 bytes
 .sbt.v3/internal.1                       |  Bin 0 -> 50042 bytes
 .sbt.v3/internal.2                       |  Bin 0 -> 50042 bytes
 .sbt.v3/internal.3                       |  Bin 0 -> 50042 bytes
 .sbt.v3/internal.4                       |  Bin 0 -> 50042 bytes
 .sbt.v3/internal.5                       |  Bin 0 -> 50042 bytes
```

Second, there are two copies of 
`test_do_sourmash_sketchdna_with_bad_scaled` and `test_do_sketch_with_seed` in this PR, and (because of the way Python works) the earlier test is shadowed by the latest test.  They copies also appear to be different. Please (a) confirm which function is the correct one, and (b) remove the wrong one.

Thanks!

**Comment by ctb** [comment]
I've completed my preliminary review; last thing I noticed is that `test_sourmash.py::test_do_sourmash_sbt_move_and_search_output` still uses runscript; is this intentional?

**Comment by ctb** [comment]
also note that I've put a checklist at the top of this PR for you to use, should you like ;)

**Comment by keyabarve** [comment]
> Hi @keyabarve I'm still working through the (many, many :) changes, but here are a few things you could dig into while I'm finishing the review.
> 
> First, I noticed that you added some new files in this PR. Was this intentional, and if so, why?
> 
No, I don't think that was intentional. I don't remember adding them though, because even now, I can't see them in the codebase on my computer. I will remove them though.
> 
> Second, there are two copies of `test_do_sourmash_sketchdna_with_bad_scaled` and `test_do_sketch_with_seed` in this PR, and (because of the way Python works) the earlier test is shadowed by the latest test. They copies also appear to be different. Please (a) confirm which function is the correct one, and (b) remove the wrong one.
> 
I will remove the ones I think are the wrong ones.

**Comment by keyabarve** [comment]
> I've completed my preliminary review; last thing I noticed is that `test_sourmash.py::test_do_sourmash_sbt_move_and_search_output` still uses runscript; is this intentional?
>
Yes, I think I left it that way. I was trying to do this: `runtmp.sourmash('search', '../short.fa.sig', 'zzz.sbt.json', '-o', 'foo')` and got this error: 
```
if self.last_result.status:
>           raise SourmashCommandFailed(self.last_result.err)
Cannot open query file '../short.fa.sig'
```
This is because the directory that this file is supposed to be in is the `newpath`.
Also, I wasn't sure how to change this part: `os.path.join(newpath`. Would it just be `runtmp.output(..)`?

**Comment by ctb** [comment]
> > I've completed my preliminary review; last thing I noticed is that `test_sourmash.py::test_do_sourmash_sbt_move_and_search_output` still uses runscript; is this intentional?
> 
> Yes, I think I left it that way. I was trying to do this: `runtmp.sourmash('search', '../short.fa.sig', 'zzz.sbt.json', '-o', 'foo')` and got this error:
> 
> ```
> if self.last_result.status:
> >           raise SourmashCommandFailed(self.last_result.err)
> Cannot open query file '../short.fa.sig'
> ```
> 
> This is because the directory that this file is supposed to be in is the `newpath`. Also, I wasn't sure how to change this part: `os.path.join(newpath`. Would it just be `runtmp.output(..)`?

oh, I see. I don't know off hand if `runtmp.sourmash` supports the in_directory parameter so you can just leave it as it is.

**Comment by keyabarve** [comment]
Alright, thanks! I believe the only thing remaining to be fixed is removing those files that have been added.

**Comment by keyabarve** [comment]
@ctb I have deleted these files:
```
.sbt.v3/0107d767a345eff67ecdaed2ee5cd7ba |  522 +++++++++++
 .sbt.v3/4e94e60265e04f0763142e20b52c0da1 |  522 +++++++++++
 .sbt.v3/60f7e23c24a8d94791cc7a8680c493f9 |  522 +++++++++++
 .sbt.v3/6d6e87e1154e95b279e5e7db414bc37b |  522 +++++++++++
 .sbt.v3/b59473c94ff2889eca5d7165936e64b3 |  522 +++++++++++
 .sbt.v3/f0c834bc306651d2b9321fb21d3e8d8f |  522 +++++++++++
 .sbt.v3/f71e78178af9e45e6f1d87a0c53c465c |  522 +++++++++++
```
but I'm not being able to delete these:
```
 .sbt.v3/internal.0                       |  Bin 0 -> 50042 bytes
 .sbt.v3/internal.1                       |  Bin 0 -> 50042 bytes
 .sbt.v3/internal.2                       |  Bin 0 -> 50042 bytes
 .sbt.v3/internal.3                       |  Bin 0 -> 50042 bytes
 .sbt.v3/internal.4                       |  Bin 0 -> 50042 bytes
 .sbt.v3/internal.5                       |  Bin 0 -> 50042 bytes
```

**Comment by ctb** [comment]
> but I'm not being able to delete these:
> 
> ```
>  .sbt.v3/internal.0                       |  Bin 0 -> 50042 bytes
>  .sbt.v3/internal.1                       |  Bin 0 -> 50042 bytes
>  .sbt.v3/internal.2                       |  Bin 0 -> 50042 bytes
>  .sbt.v3/internal.3                       |  Bin 0 -> 50042 bytes
>  .sbt.v3/internal.4                       |  Bin 0 -> 50042 bytes
>  .sbt.v3/internal.5                       |  Bin 0 -> 50042 bytes
> ```

could you describe how your trying to delete them - the process or commands - here, and work with @mr-eyes and @hehouts to remove them, please?

**Comment by mr-eyes** [comment]
Hi @keyabarve 
In the project root directory, just remove the ".sbt.v3" directory and then commit/push. This should resolve the problem.

If you can't delete them in this normal way, they might be opened/used by another process. Please make sure there is no any sourmash processes running in the background.

**Comment by mr-eyes** [comment]
Hi @keyabarve, is this PR ready for review/merge, or do you still have WIP?

**Comment by ctb** [comment]
> Hi @keyabarve, is this PR ready for review/merge, or do you still have WIP?

Now that the files have been removed, I think we're ready to merge. I'll wait for @keyabarve to have a chance to comment, but I've just updated it from `latest` in anticipation :)

**Review by ctb — APPROVED** [review]

**Pull request merged**
