### PR TITLE
[MRG] Add `FrozenMinHash`

### PR DESCRIPTION
**Pull request by ctb**
Adds a `FrozenMinHash` type that is returned by `SourmashSignature.minhash`.

Also:
* adds a `MinHash` method, `to_mutable()`, that returns `self` for `MinHash` and a mutable copy for `FrozenMinHash`.
* adds `to_frozen()` method that does the converse

Very few changes are required to make all the tests pass. The ease of doing this suggests to me that this is a Good Change.

Explores #1494.

### CODE REVIEW

**Comment by ctb** [comment]
The `compare -p` hang is caused by the following:
```
% sourmash compare -p 2 tests/test-data/{2,47,63}.fa.sig  -k 31
...
  File "/Users/t/miniconda3/envs/py37/lib/python3.7/multiprocessing/queues.py", line 354, in get
    return _ForkingPickler.loads(res)
  File "/Users/t/dev/sourmash/src/sourmash/minhash.py", line 261, in __setstate__
    self.add_many(mins)
  File "/Users/t/dev/sourmash/src/sourmash/minhash.py", line 661, in add_many
    raise TypeError('ImmutableMinHash does not support modification')
TypeError: ImmutableMinHash does not support modification
```

no clear way how to fix this, but I'm sure it'll be simple once I understand the problem better :).

related to https://bugs.python.org/issue35311

Might be something we can fix by providing a `__new__` although maybe we'd also have to specify a pickling protocol version per https://stackoverflow.com/questions/36672075/why-isnt-pickle-calling-new-like-the-documentation-says

Mmmmh, or we can fix it by providing our own `__setstate__`... that seems to work! Fixed in 1b2afdcc

**Comment by ctb** [comment]
I dunno @luizirber this actually pretty do-able. Thoughts on merging this? The docs should probably be updated if so.

**Comment by ctb** [comment]
hmm, one addition to do: replace the calls to `MinHash` with calls to whatever the class type is.

ref https://stackoverflow.com/questions/50724504/how-to-define-deep-copy-of-subclass-if-super-class-has-customized-deep-copy

**Comment by ctb** [comment]
Changed over to `FrozenMinHash`.

I think the main thing to add is some checks that `.mutable()` and `.immutable()` are working as we expect and in particular that `.mutable()` is making a _copy_ of the `FrozenMinHash`. The logic is simple enough so I suspect they are, but it's always nice to pin it down.

Also want to think about whether `MinHash.mutable()` should make a copy or not. Right now it DOES.

**Comment by ctb** [comment]
Curious what you think, @luizirber - should I propose this for merge, or just leave it for now? I don't have a strong opinion other than that this contains the potential for significant optimization down the road, so baking it in now seems like a not bad idea (since it's really easy!)

**Comment by luizirber** [comment]
I think we should go for a merge.

> Also want to think about whether `MinHash.mutable()` should make a copy or not. Right now it DOES.

This tripped me a bit while reviewing the code, because places that had `copy.copy(mh)` now have `mh.mutable()` and it is not clear from the `.mutable()` name that a copy is being made...

This is not necessarily pythonic, but in Rust there are usually conventions around `.to_*` and `.into_*` methods to return something that creates a new one, or consume something and return it. For example, in this case we could have
`.to_mutable()` for transforming the current MinHash to a mutable version (with copy) and
`.into_mutable()` to take this MinHash and make it mutable (without copy, consuming the previous minhash).
Not sure if this is clearer, tho :sweat_smile:

**Comment by ctb** [comment]
> > Also want to think about whether `MinHash.mutable()` should make a copy or not. Right now it DOES.
> 
> This tripped me a bit while reviewing the code, because places that had `copy.copy(mh)` now have `mh.mutable()` and it is not clear from the `.mutable()` name that a copy is being made...

yep

> This is not necessarily pythonic, but in Rust there are usually conventions around `.to_*` and `.into_*` methods to return something that creates a new one, or consume something and return it. For example, in this case we could have
> `.to_mutable()` for transforming the current MinHash to a mutable version (with copy) and
> `.into_mutable()` to take this MinHash and make it mutable (without copy, consuming the previous minhash).
> Not sure if this is clearer, tho 😅

right, I'm on board with the general idea. I will maybe try`to_mutable()` and `to_frozen()`; I'm not sure `into_mutable()` makes sense, but maybe `into_frozen()` does (since you'd get good error messages). I don't really like changing the classes underneath by policy (independent of what my code actually does :).

**Comment by ctb** [comment]
Ready for review, @luizirber @bluegenes

**Review by luizirber — APPROVED** [review]

**Pull request merged**
