### PR TITLE
[MRG] Add `FrozenSourmashSignature`

### PR DESCRIPTION
**Pull request by ctb**
Adds a `FrozenSourmashSignature` class, and provides sensible `to_mutable()` and `to_frozen()` methods on `SourmashSignature` and `FrozenSourmashSignature`. Provides an `update()` context manager that wraps changes so that a `FrozenSourmashSignature` is left at the end.

Complement to #1508, which did this with `MinHash`.

As with #1508, very few changes are required to make all the tests pass. The ease of doing this suggests to me that this is a Good Change.

Also as with #1508, I really like this updated code; it's so nice and clear!

I am hoping that these changes make it easier for @luizirber in Rust/Python interaction.

On the other hand, this could break some 3rd party code (as #1508 did :). Admittedly we are the owners of most of that code, but 🤷 not sure if we should delay this 'til 5.0. On the other hand, could fit nicely with a 4.5.0 release.

TODO:
- [x] update places that unnecessarily call `flatten` and `downsample` (b/c signatures are already flat and/or downsampled)
- [x] check that `SourmashSignature` by default owns a frozen `MinHash` (I think it does, but confirm)
- [x] check that `SourmashSignature.to_frozen()` also freezes the `MinHash` object.
- [x] maybe make a new method that does the `ss = ss.to_mutable(); ss.minhash = xyz; ss = ss.to_frozen()` dance;
- [x] OR, use a context manager? `with sig.mutate() as sig:`?
- [x] revisit `into_frozen()` and `into_mutable()`
- [x] add docstrings :)
- [x] consider making error messages clearer & providing guidance around using `to_mutable()`

### CODE REVIEW

**Comment by ctb** [comment]
@luizirber opinions?

**Comment by ctb** [comment]
Ready for review & merge @sourmash-bio/devs !

**Comment by ctb** [comment]
hi @luizirber I think this PR is best reviewed by you, if you have time. It's a quick read, I promise ;). And you might have a suggestion for how to improve, too - I'm not thrilled with the context manager syntax I use.

**Comment by luizirber** [comment]
I have a bunch of commits in #2230 that flip the MinHash to default to large ones (b-tree based) and expose the Frozen ones (vec-based), should I add the commits here or make a new PR merging into this one?

(I can also just merge them together in #2230, since that will be a breaking change version bump on the Rust side and I would like to avoid doing two in a row :grimacing: )

**Comment by ctb** [comment]
> I have a bunch of commits in #2230 that flip the MinHash to default to large ones (b-tree based) and expose the Frozen ones (vec-based), should I add the commits here or make a new PR merging into this one?
> 
> (I can also just merge them together in #2230, since that will be a breaking change version bump on the Rust side and I would like to avoid doing two in a row 😬 )

your call - if last option is easiest, go for it!

**Review by luizirber — APPROVED** [review]

**Comment by luizirber** [comment]
I tested out with the pile of changes coming in #2230 and it works. In the future might want to avoid all the copying, but as you pointed in the comment for the context manager it is hard to track bugs otherwise...

Another future optimization is being more strict on the Mutable/Frozen on the Rust side, right now they map to
- Mutable: `KmerMinHashBTree`
- Frozen: `KmerMinHash`
but they are both mutable (it's just that the Frozen one is much slower to mutate with large sketches).

**Comment by ctb** [comment]
awesome, thanks!! should I merge, then?

**Comment by luizirber** [comment]
> awesome, thanks!! should I merge, then?

Yup, go for it!

**Comment by ctb** [comment]
🎉

**Comment by ctb** [comment]
> In the future might want to avoid all the copying, but as you pointed in the comment for the context manager it is hard to track bugs otherwise...

I would have put more effort in to this, but note that `SourmashSignature` really only contains `name` and `filename`. The `.minhash` property is a `FrozenMinHash` that is copied around by reference. So all the copying doesn't really matter for efficiency, or at least that's what I decided after reading through the code a bunch of times :)

**Pull request merged**
